from classes import Task


tasks = [
  Task('1 Easy Clue Scroll', 10),
  Task('1 Medium Clue Scroll', 10),
  Task('25 Easy Clue Scrolls', 10),
  Task('Achieve Your First Level Up', 10),
  Task('Achieve Your First Level 5', 10),
  Task('Achieve Your First Level 10', 10),
  Task('Achieve Your First Level 20', 10),
  Task('Build a Room in Your Player Owned House', 10),
  Task('Burn Some Coloured Logs', 10),
  Task('Burn Some Food', 10),
  Task('Burn Some Normal Logs', 10),
  Task('Burn Some Oak Logs', 10),
  Task('Bury Some Bones', 10),
  Task('Buy Something From Trader Crewmembers', 10),
  Task('Cast Home Teleport', 10),
  Task('Catch a Baby Impling', 10),
  Task('Catch a Butterfly', 10, '**fixme**'),
  Task('Catch a Herring', 10),
  Task('Catch a Shrimp', 10),
  Task('Catch an Anchovy', 10),
  Task('Check Your Slayer Task', 10),
  Task('Chop Some Logs With a Steel Axe', 10),
  Task('Chop Some Logs', 10),
  Task('Clean a Grimy Guam', 10),
  Task('Complete 1 Slayer Task', 10),
  Task('Complete a Rooftop Agility Course', 10),
  Task('Complete the Leagues Tutorial', 10),
  Task('Cook Shrimp', 10),
  Task('Craft a Leather Body', 10, '**fixme**'),
  Task('Craft Any Rune', 10),
  Task('Create a Compost Potion', 10),
  Task('Create an Antipoison', 10),
  Task('Cry in a wheat field', 10),
  Task('Cut a Sapphire', 10),
  Task('Dance in a graveyard', 10),
  Task('Defeat a Goblin', 10),
  Task('Defeat a Guard', 10),
  Task('Defeat a Moss Giant', 10),
  Task('Drink a Strength Potion', 10),
  Task('Dye a cape orange', 10),
  Task('Eat some Purple Sweets', 10),
  Task('Enter Puro Puro from Gielinor', 10),
  Task('Enter your Player Owned House', 10),
  Task('Equip a Full Mithril Set', 10),
  Task('Equip a Maple Shortbow', 10),
  Task('Equip a Mithril Weapon', 10),
  Task('Equip a Spiny Helmet', 10),
  Task('Equip a Studded Body and Chaps', 10),
  Task('Equip a Willow Shield', 10),
  Task('Equip an Elemental Staff', 10),
  Task('Equip some Black armour', 10),
  Task('Equip some Steel armour', 10),
  Task('Fletch 1000 arrow shafts', 10),
  Task('Fletch 150 Iron Arrows', 10),
  Task('Fletch 25 Oak Stocks', 10),
  Task('Fletch an Oak Shortbow', 10),
  Task('Fletch Some Arrow Shafts', 10),
  Task('Gain a Unique Item From a Beginner Clue', 10),
  Task('Gain a Unique Item From an Easy Clue', 10),
  Task('Have a conversation with a cat', 10, '**fixme**'),
  Task('Kill a Necromancer', 10, '**fixme**'),
  Task('Light a Torch', 10),
  Task('Locate a Runecrafting Altar With a Talisman', 10),
  Task('Make an Attack Potion', 10),
  Task('Make some Flour', 10),
  Task('Mine 10 Tin Ore', 10),
  Task('Mine 15 coal', 10),
  Task('Mine some Copper Ore', 10),
  Task('Mine some Ore With a Steel Pickaxe', 10),
  Task('Obtain a Bird Nest', 10),
  Task('Obtain a Casket from Fishing', 10),
  Task('Obtain a Gem While Mining', 10),
  Task('Obtain a Mark of Grace', 10),
  Task('Open 28 Coin Pouches At Once', 10),
  Task('Open the Leagues Menu', 10),
  Task('Pickpocket a Citizen', 10),
  Task('Plant Seeds in an Allotment Patch', 10, '**fixme**'),
  Task('Protect Your Crops', 10),
  Task('Purchase a Player Owned House', 10),
  Task('Rake a Farming Patch', 10),
  Task('Reach Base Level 5', 10),
  Task('Reach Base Level 10', 10),
  Task('Reach Base Level 20', 10),
  Task('Reach Combat Level 10', 10),
  Task('Reach Combat Level 25', 10),
  Task('Reach Total Level 100', 10),
  Task('Reach Total Level 250', 10),
  Task('Reach Total Level 500', 10),
  Task('Receive a Slayer Task', 10),
  Task('Restore 5 Prayer Points at an Altar', 10),
  Task('Scrape some blue dragonhide', 10),
  Task('Smelt a Bronze Bar', 10),
  Task('Smelt an Iron Bar', 10),
  Task('Smith 150 Iron Arrowtips', 10),
  Task('Smith a Bronze full helm', 10),
  Task('Smith a Bronze plateskirt', 10),
  Task('Snare a Bird', 10),
  Task('Spin a Ball of Wool', 10),
  Task('Steal a Chocolate Slice', 10, '**fixme**'),
  Task('Steal Some Silk', 10, '**fixme**'),
  Task('Successfully Cook 5 Pieces of Food', 10),
  Task('Successfully Cut a Red Topaz', 10),
  Task('Superhuman Strength and Improved Reflexes', 10),
  Task('Turn any Logs Into a Plank', 10),
  Task('Use a herring on a tree', 10),
  Task('Visit Deaths Domain', 10),
  Task('Visit the Rune Essence Mine', 10),
  Task('Become a mushroom', 10, 'a'),
  Task('Complete a Game of Novice Pest Control', 10, 'a'),
  Task('Craft an Air Rune', 10, 'a'),
  Task('Defeat a Black Demon in Asgarnia', 10, 'a'),
  Task('Defeat a Blue Dragon in Asgarnia', 10, 'a'),
  Task('Defeat a Troll in Asgarnia', 10, 'a'),
  Task('Defeat the Evil chicken', 10, 'a'),
  Task('Eat a magic cabbage', 10, 'a'),
  Task('Enter the Taverley Dungeon', 10, 'a'),
  Task('Equip an Imcando Hammer', 10, 'a'),
  Task('Give Thurgo a redberry pie', 10, '**fixme**'),
  Task('Kill a port sarim prisoner', 10, 'a'),
  Task('Move Your House to Taverley', 10, 'a'),
  Task('Open an Ornate Lockbox', 10, 'a'),
  Task('Pay Atlas to re-train you', 10, 'a'),
  Task('Receive a Slayer Task From Turael or Spria', 10, 'a'),
  Task('Talk to the Mysterious Old Man in Falador', 10, 'a'),
  Task('Unlock a Gate in Taverley Dungeon', 10, 'a'),
  Task('1 Tempoross Kill', 10, 'd'),
  Task('Complete the Al Kharid Agility Course', 10, 'd'),
  Task('Complete The Golem', 10, 'd'),
  Task('Craft a Fire Rune', 10, 'd'),
  Task('Cut a Cactus in the Kharidian Desert', 10, 'd'),
  Task('Defeat an Al Kharid Warrior', 10, 'd'),
  Task('Enter Sophanem', 10, 'd'),
  Task('Enter the Kalphite Lair', 10, 'd'),
  Task('Get sent to port sarim jail', 10, '**fixme**'),
  Task('Go Through the Al Kharid Gate', 10, 'd'),
  Task('Kill a Seagull in the Desert', 10, 'd'),
  Task('Obtain Fossilised Dung', 10, 'd'),
  Task('Pick a Winter Sqirk', 10, 'd'),
  Task('Pick up a cabbage in the Citharede Abbey', 10, 'd'),
  Task('Room 1 of Pyramid Plunder', 10, 'd'),
  Task('Room 2 of Pyramid Plunder', 10, 'd'),
  Task('Room 3 of Pyramid Plunder', 10, 'd'),
  Task('Take a Carpet Ride from Pollnivneach to Sophanem', 10, 'd'),
  Task('Tan a Cow Hide in the Kharidian Desert', 10, 'd'),
  Task('Turn in a Winter Sqirkjuice to Osman', 10, 'd'),
  Task('Chop down an arctic pine tree', 10, 'f'),
  Task('Defeat a Cockatrice in the Fremennik Province', 10, 'f'),
  Task('Defeat a Pyrefiend in the Fremennik Province', 10, 'f'),
  Task('Defeat a Rock Crab in the Fremennik Province', 10, 'f'),
  Task('Defeat a Troll in the Fremennik Province', 10, 'f'),
  Task('Deposit an Item Using Peer the Seer', 10, 'f'),
  Task('Kill a Yak', 10, 'f'),
  Task('Switch to the Lunar Spellbook', 10, 'f'),
  Task('Use the Bank on Jatizso', 10, 'f'),
  Task('Use the Bank on Lunar Isle', 10, 'f'),
  Task('Use the Bank on Neitiznot', 10, 'f'),
  Task('Brimstail Rune Essence Mine teleport', 10, 'k'),
  Task('Catch a Crimson Swift in the Feldip Hills', 10, 'k'),
  Task('Catch a wild kebbit', 10, 'k'),
  Task('Complete a Fishing Trawler Game', 10, 'k'),
  Task('Complete Fishing Contest', 10, 'k'),
  Task('Complete Monks Friend', 10, 'k'),
  Task('Complete Sea Slug', 10, 'k'),
  Task('Complete the Gnome Stronghold Agility Course', 10, 'k'),
  Task('Defeat a Bloodveld in Kandarin', 10, 'k'),
  Task('Defeat a Fire Giant in Kandarin', 10, 'k'),
  Task('Drink a Poison Chalice', 10, 'k'),
  Task('Equip a Marksman Chompy Hat', 10, 'k'),
  Task('Flex in front of The Guns', 10, '**fixme**'),
  Task('Get Stung By Bees', 10, 'k'),
  Task('Kill a Newtroost', 10, 'k'),
  Task('Kill Salarin the Twisted', 10, 'k'),
  Task('Pick Wheat in Catherby', 10, 'k'),
  Task('Prove yourself to Ponts', 10, '**fixme**'),
  Task('Receive a Slayer Task From Nieve/Steve', 10, 'k'),
  Task('Visit the Tree Gnome Stronghold', 10, 'k'),
  Task('Visit the Tree Gnome Village', 10, 'k'),
  Task('Catch a Karambwanji', 10),
  Task('Defeat a Greater Demon on Karamja', 10),
  Task('Defeat a TzHaar', 10),
  Task('Enter the Brimhaven Dungeon', 10),
  Task('Pick a Pineapple on Karamja', 10),
  Task('Receive a Slayer Task From Duradel', 10),
  Task('Receive an Agility Arena Ticket', 10),
  Task('1 Sarachnis Kill', 10, 'z'),
  Task('1 Wintertodt Kill', 10, 'z'),
  Task('Brutally murder Conrad King', 10, 'z'),
  Task('Complete 1 Farming Contract', 10, 'z'),
  Task('Complete Architectural Alliance', 10, 'z'),
  Task('Complete Ascent of Arceuus', 10, 'z'),
  Task('Complete Client of Kourend', 10, '**fixme**'),
  Task('Complete Depths of Despair', 10, 'z'),
  Task('Complete Forsaken Tower', 10, 'z'),
  Task('Complete In Search Of Knowledge', 10, 'z'),
  Task('Complete Queen of Thieves', 10, 'z'),
  Task('Complete Tale Of The Righteous', 10, 'z'),
  Task('Drink a LizardKicker', 10, 'z'),
  Task('Equip a Protest Banner', 10, 'z'),
  Task('Fish an old boot in stranglewood', 10, '**fixme**'),
  Task('Open 1 Grubby Chest', 10, 'z'),
  Task('Open 15 Grubby Chests', 10, 'z'),
  Task('Pray at an altar in Molch while poisoned.', 10, 'z'),
  Task('Receive a Konar Slayer Task', 10, 'z'),
  Task('Steal 1 Artefact', 10, 'z'),
  Task('Turn in 1 Library Book', 10, 'z'),
  Task('Build a Bank on Fossil Island', 10),
  Task('Charm Gertrude', 10, '**fixme**'),
  Task('Chop a log from a potato tree', 10),
  Task('Churn some butter', 10),
  Task('Complete Gertrudes Cat', 10),
  Task('Complete Romeo & Juliet', 10),
  Task('Complete Sheep Shearer', 10),
  Task('Complete the Draynor Agility Course', 10),
  Task('Complete the Natural History Quiz', 10),
  Task('Complete the Varrock Agility Course', 10),
  Task('Complete Vampyre Slayer', 10),
  Task('Craft 50 Water Runes', 10),
  Task('Defeat the Lesser Demon in the Wizards Tower', 10),
  Task('Enter Draynor Manor', 10),
  Task('Enter Zanaris', 10),
  Task('Equip Some Fancy, Fancier or Fighting Boots', 10),
  Task('Feed a draynor guard some stew', 10),
  Task('Fully Unlock the Mycelium Transportation System', 10),
  Task('Get a chair to follow you', 10),
  Task('Get your revenge against a Dark Wizard', 10),
  Task('Have Elsie tell you a story', 10),
  Task('Have Ned make you some rope', 10),
  Task('Insult Aggie the Witch', 10),
  Task('Milk a cow', 10),
  Task('Pet a Stray Dog in Varrock', 10),
  Task('Pet the Museum Camp dog', 10),
  Task('Pickpocket a H.A.M. Member', 10),
  Task('Receive a Slayer Task From Vannaka', 10),
  Task('Slash a web in varrock sewers', 10),
  Task('Steal From the Varrock Tea Stall', 10),
  Task('Taste a Dorgeshuun Delicacy', 10),
  Task('Travel to Fossil Island', 10),
  Task('Use a Fairy Ring', 10),
  Task('Use the Range in Lumbridge Castle', 10),
  Task('Complete an Easy Temple Trek', 10, 'm'),
  Task('Craft a Snelm', 10, 'm'),
  Task('Defeat a Ghast', 10, 'm'),
  Task('Defeat a Werewolf in Morytania', 10, 'm'),
  Task('Defeat One of Fenkenstrains Experiments', 10, 'm'),
  Task('Open a Bronze Chest', 10, 'm'),
  Task('Receive a Slayer Task From Mazchna', 10, 'm'),
  Task('Visit Harmony Island', 10, 'm'),
  Task('Visit Mos LeHarmless', 10, 'm'),
  Task('Visit Port Phasmatys', 10, 'm'),
  Task('Charter a Ship From Prifddinas to Port Tyras', 10, 't'),
  Task('Cook a Rabbit in Tirannwn', 10, 't'),
  Task('Cross a Trap in Isafdar', 10, 't'),
  Task('Defeat a Moss Giant in Tirannwn', 10, 't'),
  Task('Defeat a Waterfiend in Tirannwn', 10, 't'),
  Task('Harvest Some Sweetcorn in Prifddinas', 10, 't'),
  Task('Talk to Ilfeen in Tirannwn', 10, 't'),
  Task('Use Broken Handzs telescope', 10, 't'),
  Task('Use the Bank in Lletya', 10, 't'),
  Task('Defeat a Chaos Dwarf in the Wilderness', 10, 'w'),
  Task('Defeat a Fire Giant in the Wilderness', 10, 'w'),
  Task('Enter the Wilderness God Wars Dungeon', 10, 'w'),
  Task('Enter the Wilderness Resource Area', 10, 'w'),
  Task('Equip a team cape', 10, 'w'),
  Task('Order a Drink at The Old Nite', 10, 'w'),
  Task('Pray at the Southern Chaos Temple', 10, 'w'),
  Task('Pray at the Western Chaos Temple', 10, 'w'),
  Task('Use a Lever to Teleport to Edgeville', 10, 'w'),
  Task('Use the Bank at the Mage Arena', 10, 'w'),
  Task('Visit Ferox Enclave', 10, 'w'),
  Task('1 Combat Achievement', 40),
  Task('1 Elite Clue Scroll', 40),
  Task('1 Hard Clue Scroll', 40),
  Task('10 Combat Achievements', 40),
  Task('100 Superior Slayer Encounters', 40),
  Task('15 Collection log slots', 40),
  Task('150 Easy Clue Scrolls', 40),
  Task('150 Medium Clue Scrolls', 40),
  Task('25 Hard Clue Scrolls', 40),
  Task('25 Medium Clue Scrolls', 40),
  Task('25 Superior Slayer Encounters', 40),
  Task('30 Collection log slots', 40),
  Task('5 Collection log slots', 40),
  Task('75 Easy Clue Scrolls', 40),
  Task('75 Medium Clue Scrolls', 40),
  Task('75 Superior Slayer Encounters', 40),
  Task('Achieve Your First Level 30', 40),
  Task('Achieve Your First Level 40', 40),
  Task('Achieve Your First Level 50', 40),
  Task('Activate Smite', 40),
  Task('Build a Mahogany Portal', 40),
  Task('Build a Waka Canoe', 40),
  Task('Build an Oak Larder', 40),
  Task('Burn 100 Willow Logs', 40),
  Task('Bury Some Wyvern or Dragon Bones', 40),
  Task('Cast a Blast Spell', 40),
  Task('Cast High Level Alchemy', 40),
  Task('Catch 100 Lobsters', 40),
  Task('Catch 50 Salmon', 40),
  Task('Catch 50 Swordfish', 40),
  Task('Catch a Swamp Lizard or Salamander', 40, '**fixme**'),
  Task('Check a grown Fruit Tree', 40),
  Task('Chop 100 Willow Logs', 40),
  Task('Chop Some Logs With a Rune Axe', 40),
  Task('Chop some Rising Roots', 40),
  Task('Clean a Grimy Avantoe', 40),
  Task('Complete 50 Laps of a Rooftop Agility Course', 40),
  Task('Complete 50 Mahogany homes contracts', 40, '**fixme**'),
  Task('Complete a Mahogany homes adept contract', 40, '**fixme**'),
  Task('Complete a Mahogany homes beginner contract', 40, '**fixme**'),
  Task('Complete a Mahogany homes novice contract', 40, '**fixme**'),
  Task('Complete the Easy Western Provinces Diary', 40, '**fixme**'),
  Task('Complete the Flowering Bush event', 40, '**fixme**'),
  Task('Complete the Medium Western Provinces Diary', 40, '**fixme**'),
  Task('Complete the Pheasant Forestry Event', 40),
  Task('Complete the Ritual Forestry Event', 40),
  Task('Complete the Struggling Sapling event', 40),
  Task('Cook 100 Lobsters', 40),
  Task('Craft 100 Unpowered Orbs', 40),
  Task('Craft 200 Essence Into Runes', 40),
  Task('Craft 4 Runes With 1 Essence', 40, '**fixme**'),
  Task('Craft a Ruby Amulet', 40),
  Task('Craft an Emerald Ring', 40),
  Task('Craft Any Combination Rune', 40),
  Task('Create a green dhide shield', 40),
  Task('Create a Guthix Rest Tea', 40, '**fixme**'),
  Task('Create a Mithril Grapple', 40),
  Task('Defeat a Lesser Demon', 40),
  Task('Defeat a Superior Slayer Creature', 40),
  Task('Defeat an Adult Chromatic Dragon', 40),
  Task('Equip a frog mask', 40),
  Task('Equip a Full Adamant Set', 40),
  Task('Equip a Full Blue Dragonhide Set', 40),
  Task('Equip a Full Green Dragonhide Set', 40),
  Task('Equip a Full Red Dragonhide Set', 40),
  Task('Equip a Full Rune Set', 40),
  Task('Equip a Granite Shield', 40, '**fixme**'),
  Task('Equip a Harpie Bug Lantern', 40),
  Task('Equip a Lava Battlestaff', 40, '**fixme**'),
  Task('Equip a Leaf-Bladed Sword', 40, '**fixme**'),
  Task('Equip a Piece of a Mystic Set', 40),
  Task('Equip a Rune Weapon', 40),
  Task('Equip a Trimmed Amulet', 40),
  Task('Equip a Wizard Robe and Hat', 40),
  Task('Equip a Yew Shortbow', 40),
  Task('Equip an Adamant Weapon', 40),
  Task('Equip an Elemental Battlestaff or Mystic Staff', 40),
  Task('Equip full Graahk, Larupia or Kyatt', 40),
  Task('Ferment 100 Jugs of Wine', 40),
  Task('Fill 3 Elite Clue Collection Log Slots', 40),
  Task('Fill 3 Hard Clue Collection Log Slots', 40),
  Task('Fill 5 Beginner Clue Collection Log Slots', 40),
  Task('Fill 5 Easy Clue Collection Log Slots', 40),
  Task('Fill 5 Medium Clue Collection Log Slots', 40),
  Task('Fill a Bucket With Supercompost', 40, '**fixme**'),
  Task('Fill a Large Pouch', 40),
  Task('Fill a Medium S.T.A.S.H. Unit', 40),
  Task('Fletch 100 Yew shortbows', 40),
  Task('Fletch a Willow Shortbow', 40),
  Task('Fletch some Broad Arrows or Bolts', 40),
  Task('Fully deplete a Blood Essence', 40, '**fixme**'),
  Task('Gain 10 Unique Items From Beginner Clues', 40),
  Task('Gain 10 Unique Items From Easy Clues', 40),
  Task('Gain 10 Unique Items From Medium Clues', 40),
  Task('Gain 5 Unique Items From Hard Clues', 40),
  Task('Gain a Unique Item From a Hard Clue', 40),
  Task('Gain a Unique Item From a Medium Clue', 40),
  Task('Harvest an Irit Leaf', 40, '**fixme**'),
  Task('Kill 6 cows in 10 seconds', 40),
  Task('Kill three chickens in 6 seconds.', 40),
  Task('Light a Bullseye Lantern', 40, '**fixme**'),
  Task('Make 30 Prayer Potions', 40),
  Task('Make a 4 dose potion', 40),
  Task('Make a Pineapple Pizza', 40),
  Task('Mine 50 Iron Ore', 40),
  Task('Mine some Ore With a Rune Pickaxe', 40),
  Task('Obtain 800 Coins From Coin Pouches At Once', 40),
  Task('Obtain a Clue Geode While Mining', 40),
  Task('Perform a Special Attack', 40),
  Task('Pickpocket a Guard', 40),
  Task('Pickpocket a Master Farmer', 40),
  Task('Pickpocket a Ranarr Seed', 40),
  Task('Reach a Prayer Bonus of 15', 40),
  Task('Reach Base Level 30', 40),
  Task('Reach Base Level 40', 40),
  Task('Reach Base Level 50', 40),
  Task('Reach Combat Level 50', 40),
  Task('Reach Combat Level 75', 40),
  Task('Reach Total Level 750', 40),
  Task('Reach Total Level 1000', 40),
  Task('Reach Total Level 1250', 40),
  Task('Read a prayer book near a lectern', 40, '**fixme**'),
  Task('Slay 250 Creatures', 40),
  Task('Smelt a Steel Bar', 40),
  Task('Smith 10 Steel bolts (unf)', 40),
  Task('Smith a Steel Platebody', 40),
  Task('Teleport Using Law Runes', 40, '**fixme**'),
  Task('Use the Protect from Melee Prayer', 40),
  Task('Charge an Amulet of Glory in the Heroes Guild', 40, 'a'),
  Task('Complete a Game of Intermediate Pest Control', 40, 'a'),
  Task('Complete A Porcine of Interest', 40, 'a'),
  Task('Complete Below Ice Mountain', 40, 'a'),
  Task('Complete Death to the Dorgeshuun', 40, 'a'),
  Task('Complete the Easy Falador Diary', 40, 'a'),
  Task('Complete the Falador Agility Course', 40, 'a'),
  Task('Complete The Lost Tribe', 40, 'a'),
  Task('Complete the Medium Falador Diary', 40, 'a'),
  Task('Craft a Body Rune', 40, 'a'),
  Task('Craft a Chaos Rune using a Chaos Core', 40, '**fixme**'),
  Task('Defeat 30 Black Dragons in Asgarnia', 40, 'a'),
  Task('Defeat a Skeletal Wyvern', 40, 'a'),
  Task('Defeat Some Animated Rune Armour', 40, 'a'),
  Task('Defeat the Giant Mole 150 Times', 40, 'a'),
  Task('Defeat the Giant Mole 50 Times', 40, 'a'),
  Task('Defeat the Giant Mole', 40, 'a'),
  Task('Enter the Crafting Guild', 40, 'a'),
  Task('Enter the Warriors Guild', 40, 'a'),
  Task('Equip a Dorgeshuun Crossbow', 40, 'a'),
  Task('Equip Amys Saw', 40, 'a'),
  Task('Equip Some Granite Legs', 40, 'a'),
  Task('Harvest Any Herb at the Troll Stronghold', 40, 'a'),
  Task('Make 20 Stamina Potions', 40, 'a'),
  Task('Make 50 Ancient Brews', 40, 'a'),
  Task('Obtain 20 Golden Nuggets', 40, 'a'),
  Task('Obtain the Plank Sack', 40, 'a'),
  Task('Open the Crystal Chest', 40, 'a'),
  Task('Pickpocket a Bullseye Lantern From a Cave Goblin', 40, 'a'),
  Task('Turn in 100 Mole Claws to Wyson the Gardener', 40, 'a'),
  Task('50 Tempoross Kills', 40, 'd'),
  Task('Cast Bones to Peaches', 40, 'd'),
  Task('Cast Ice Rush', 40, 'd'),
  Task('Catch 30 Orange Salamanders', 40, 'd'),
  Task('Check a grown Cactus', 40, 'd'),
  Task('Complete Shadow of the Storm', 40, 'd'),
  Task('Complete Sleeping Giants', 40, 'd'),
  Task('Complete Spirits of the Elid', 40, 'd'),
  Task('Complete the Easy Desert Diary', 40, 'd'),
  Task('Complete the Medium Desert Diary', 40, 'd'),
  Task('Craft a Lava Rune at the Fire Altar', 40, 'd'),
  Task('Create the Divine Rune pouch', 40, 'd'),
  Task('Defeat a Crocodile', 40, 'd'),
  Task('Defeat a Dust Devil in the Kharidian Desert', 40, 'd'),
  Task('Defeat a Kalphite Guardian', 40, 'd'),
  Task('Defeat a Scarab Mage', 40, 'd'),
  Task('Equip the Amulet of the eye under the Portal', 40, 'd'),
  Task('Equip the Colossal Blade', 40, 'd'),
  Task('Equip the Ring of the elements', 40, 'd'),
  Task('Equip the Tome of Water', 40, 'd'),
  Task('Giants Foundry 100 quality sword', 40, 'd'),
  Task('Giants Foundry 25 hand-ins', 40, 'd'),
  Task('Giants Foundry 50 quality sword', 40, 'd'),
  Task('Guardians of the Rift 1 Rift closed', 40, 'd'),
  Task('Kill a Kalphite with the Keris Partisan', 40, 'd'),
  Task('Make a Combat Potion', 40, 'd'),
  Task('Mine 30 Chunks of Granite', 40, 'd'),
  Task('Move Your House to Pollnivneach', 40, 'd'),
  Task('Obtain the Big Harpoonfish', 40, 'd'),
  Task('Pick a Autumn Sqirk', 40, 'd'),
  Task('Pick a Spring Sqirk', 40, 'd'),
  Task('Pickpocket a Bandit in the Bandit Camp', 40, 'd'),
  Task('Pray at the Elidinis Statuette', 40, 'd'),
  Task('Room 4 of Pyramid Plunder', 40, 'd'),
  Task('Room 5 of Pyramid Plunder', 40, 'd'),
  Task('Room 6 of Pyramid Plunder', 40, 'd'),
  Task('Smith 1,000 Mithril Dart Tips', 40, 'd'),
  Task('Turn in 10 Spring Sqirkjuices to Osman', 40, 'd'),
  Task('Turn in a Pyramid Top to Simon Templeton', 40, 'd'),
  Task('Cast Moonclan Teleport', 40, 'f'),
  Task('Catch a Snowy Knight', 40, 'f'),
  Task('Complete Olafs Quest', 40, 'f'),
  Task('Complete Royal Trouble', 40, 'f'),
  Task('Complete the Easy Fremennik Diary', 40, 'f'),
  Task('Complete the Medium Fremennik Diary', 40, 'f'),
  Task('Complete the Penguin Agility Course', 40, 'f'),
  Task('Complete Throne of Miscellania', 40, 'f'),
  Task('Craft 50 Astral Runes', 40, 'f'),
  Task('Defeat a Basilisk Knight', 40, 'f'),
  Task('Defeat a Dagannoth in the Fremennik Province', 40, 'f'),
  Task('Defeat a Jelly in the Fremennik Province', 40, 'f'),
  Task('Defeat a Kurask in the Fremennik Province', 40, 'f'),
  Task('Defeat a Turoth in the Fremennik Province.', 40, 'f'),
  Task('Equip a Brine Sabre', 40, 'f'),
  Task('Equip a full set of Yakhide Armour', 40, 'f'),
  Task('Equip a Helm of Neitiznot', 40, 'f'),
  Task('Kill 8 penguins within 5 seconds', 40, 'f'),
  Task('Move Your House to Rellekka', 40, 'f'),
  Task('Reach the lighthouse via stepping stones', 40, '**fixme**'),
  Task('Unlock Free Use of the Blast Furnace', 40, 'f'),
  Task('Use Some Icy Basalt to Teleport to Weiss', 40, 'f'),
  Task('Catch a Monkfish', 40, 'k'),
  Task('Catch a Red Salamander', 40, 'k'),
  Task('Check a grown Papaya Tree in the Gnome Stronghold', 40, 'k'),
  Task('Complete Elemental Workshop II', 40, 'k'),
  Task('Complete the Barbarian Outpost Agility Course', 40, 'k'),
  Task('Complete the Easy Ardougne Diary', 40, 'k'),
  Task('Complete the Easy Kandarin Diary', 40, 'k'),
  Task('Complete the Medium Ardougne Diary', 40, 'k'),
  Task('Complete the Medium Kandarin Diary', 40, 'k'),
  Task('Complete the Observatory Quest', 40, 'k'),
  Task('Complete Tower of Life', 40, 'k'),
  Task('Defeat a Mithril Dragon', 40, 'k'),
  Task('Defeat a Tortoise With Riders in Kandarin', 40, 'k'),
  Task('Defeat the Penance Queen', 40, 'k'),
  Task('Defeat the Thermonuclear Smoke Devil', 40, 'k'),
  Task('Enter the Fishing Guild', 40, 'k'),
  Task('Enter the Ranging Guild', 40, 'k'),
  Task('Enter the Wizards Guild', 40, 'k'),
  Task('Equip a Dragon Scimitar', 40, 'k'),
  Task('Equip a Monkey Backpack', 40, 'k'),
  Task('Equip a Spottier Cape', 40, 'k'),
  Task('Equip an Ibans Staff (u)', 40, '**fixme**'),
  Task('Equip an Ogre Forester Chompy Hat', 40, 'k'),
  Task('Kill a Swordchick', 40, 'k'),
  Task('Move Your House to Yanille', 40, 'k'),
  Task('Pickpocket a Knight of Ardougne 50 Times', 40, 'k'),
  Task('Score a Goal in Gnomeball', 40, 'k'),
  Task('Sell 20 Iron Sheets', 40, 'k'),
  Task('Set Up a Dwarf Cannon', 40, '**fixme**'),
  Task('Spawn a Skeletal Mage', 40, '**fixme**'),
  Task('Trade in a cat for death runes', 40, 'k'),
  Task('Trap a Spined Larupia in the Feldip Hills', 40, 'k'),
  Task('Use the Chivalry Prayer', 40, 'k'),
  Task('Win a Game of Castle Wars', 40, 'k'),
  Task('Buy a Snapdragon From Pirate Jackie the Fruit', 40),
  Task('Catch 50 Karambwan', 40),
  Task('Catch a Salmon on Karamja', 40),
  Task('Complete the Easy Karamja Diary', 40),
  Task('Complete the Medium Karamja Diary', 40),
  Task('Craft 50 Nature Runes', 40),
  Task('Defeat a Steel Dragon on Karamja', 40),
  Task('Enter the Tai Bwo Wannai Hardwood Grove', 40),
  Task('Equip a Full Tai Bwo Wannai Villager Set', 40),
  Task('Equip a Matching Tribal Mask and Broodoo Shield', 40),
  Task('Fill a Crate With Bananas', 40),
  Task('Mine 5 gem rocks in a row without failing', 40, '**fixme**'),
  Task('250 Lizardmen Shaman Kills', 40, 'z'),
  Task('50 Sarachnis Kills', 40, 'z'),
  Task('50 Wintertodt Kills', 40, 'z'),
  Task('Cast Kourend Castle Teleport', 40, 'z'),
  Task('Cast Resurrect Crops', 40, 'z'),
  Task('Chop a Magic Log at the Forsaken Tower', 40, 'z'),
  Task('Complete Getting Ahead', 40, 'z'),
  Task('Defeat a Drake', 40, 'z'),
  Task('Enter the Farming Guilds Mid Tier', 40, 'z'),
  Task('Enter the Woodcutting Guild', 40, 'z'),
  Task('Equip Tier 5 Shayzien Armour', 40, 'z'),
  Task('Equip Xerics Talisman', 40, 'z'),
  Task('Friend of House Arceuus', 40, 'z'),
  Task('Friend of House Hosidius', 40, 'z'),
  Task('Friend of House Piscarilius', 40, 'z'),
  Task('Friend of House Shayzien', 40, 'z'),
  Task('Headbang with KetSal Kuk', 40, 'z'),
  Task('Inferior Demonbane Demon Kill', 40, 'z'),
  Task('Kill a creature in Mount Karuulm', 40, 'z'),
  Task('Kourend and Kebos Easy Diary Tasks', 40, 'z'),
  Task('Kourend and Kebos Medium Diary Tasks', 40, 'z'),
  Task('Obtain Adamantite Ore at the Blast Mine', 40, 'z'),
  Task('Open 30 Grubby Chests', 40, 'z'),
  Task('Plant 100 Golovanova Seeds', 40, 'z'),
  Task('Purchase a Seed Box', 40, 'z'),
  Task('Smelt a mithril bar in a volcanic fissure', 40, 'z'),
  Task('Steal 15 Artefacts', 40, 'z'),
  Task('Steal 30 Artefacts', 40, 'z'),
  Task('Teleport to Xerics Honour', 40, 'z'),
  Task('Turn in 25 Library Books', 40, 'z'),
  Task('Turn in 50 Library Books', 40, 'z'),
  Task('Catch 50 Implings in Puro-Puro', 40),
  Task('Chop a Sulliuscep Cap', 40),
  Task('Complete 10 Laps of the Draynor Agility Course', 40),
  Task('Complete 10 Laps of the Varrock Agility Course', 40),
  Task('Complete a Souls Bane', 40),
  Task('Complete a task for the Wise Old Man', 40),
  Task('Complete a Volcanic Mine Game', 40),
  Task('Complete Demon Slayer', 40),
  Task('Complete Rune Mysteries', 40),
  Task('Complete the Easy Lumbridge & Draynor Diary', 40),
  Task('Complete the Easy Varrock Diary', 40),
  Task('Complete the Medium Lumbridge & Draynor Diary', 40),
  Task('Complete the Medium Varrock Diary', 40),
  Task('Craft 50 Cosmic Runes', 40),
  Task('Defeat a Fossil Island Wyvern', 40),
  Task('Defeat a Wall Beast', 40),
  Task('Defeat an Ancient Wyvern', 40),
  Task('Defeat Bryophyta', 40),
  Task('Defeat Obor', 40),
  Task('Dismantle 20 Filled Bird Houses', 40),
  Task('Drink From the Tears of Guthix', 40),
  Task('Enter the Cooks Guild', 40),
  Task('Equip Some Mithril Gloves', 40, '**fixme**'),
  Task('Equip the Forestry Basket', 40),
  Task('Have the wise Old Man get angry with you.', 40, '**fixme**'),
  Task('Obtain a pufferfish from Drift Net Fishing', 40),
  Task('Open the Dark Chest', 40),
  Task('Pan for an Uncut Jade', 40),
  Task('Set up a Yew Bird House', 40),
  Task('Use a Digsite Pendant to Teleport to Fossil Island', 40),
  Task('Use Enriched Bones on the Strange Machine', 40),
  Task('Win a Game of Soul Wars', 40),
  Task('Achieve 100% Shades of MortTon Sanctity', 40, 'm'),
  Task('Assemble a Slayer Helm', 40, 'm'),
  Task('Burn 20 Pyre Logs', 40, 'm'),
  Task('Catch a Swamp Lizard in Morytania', 40, 'm'),
  Task('Complete a Medium Temple Trek', 40, 'm'),
  Task('Complete A Taste of Hope', 40, 'm'),
  Task('Complete Ghosts Ahoy', 40, '**fixme**'),
  Task('Complete Haunted Mine', 40, 'm'),
  Task('Complete the Canifis Agility Course', 40, 'm'),
  Task('Complete the Easy Morytania Diary', 40, 'm'),
  Task('Complete the Medium Morytania Diary', 40, 'm'),
  Task('Complete the Werewolf Agility Course', 40, 'm'),
  Task('Convert 2,000 Daeyalt Shards Into Essence', 40, 'm'),
  Task('Craft a Rune Using Daeyalt Essence', 40, 'm'),
  Task('Defeat a Fiyr Shade', 40, 'm'),
  Task('Defeat a Gargoyle in Morytania', 40, 'm'),
  Task('Defeat a Vyrewatch Sentinel', 40, 'm'),
  Task('Defeat an Abyssal Demon in Morytania', 40, 'm'),
  Task('Equip a Piece of any Barrows Armour Set', 40, 'm'),
  Task('Equip a Salve Amulet (e)', 40, 'm'),
  Task('Feed a ghast some sweets', 40, 'm'),
  Task('Floor 1 of the Hallowed Sepulchre', 40, 'm'),
  Task('Floor 2 of the Hallowed Sepulchre', 40, 'm'),
  Task('Have the Taxidermist stuff something for you', 40, '**fixme**'),
  Task('Loot a Barrows Chest', 40, 'm'),
  Task('Open a Black Chest', 40, 'm'),
  Task('Pet Frank', 40, 'm'),
  Task('Telegrab a Bloody bracer', 40, 'm'),
  Task('Check a grown Papaya Tree in Lletya', 40, 't'),
  Task('Craft 50 Death Runes', 40, 't'),
  Task('Defeat a Bloodveld in Tirannwn', 40, 't'),
  Task('Defeat a Kurask in Tirannwn', 40, 't'),
  Task('Defeat an Elf in Tirannwn', 40, 't'),
  Task('Kill a Black Dragon in Tirannwn', 40, 't'),
  Task('Move Your House to Prifddinas', 40, 't'),
  Task('Ring all of the Prifddinas bells', 40, 't'),
  Task('Use an Elven Teleport Crystal', 40, 't'),
  Task('Bury Some Lava Dragon Bones', 40, 'w'),
  Task('Cast Claws of Guthix', 40, 'w'),
  Task('Cast Flames of Zamorak', 40, 'w'),
  Task('Cast Saradomin Strike', 40, 'w'),
  Task('Catch a Black Chinchompa', 40, 'w'),
  Task('Catch a Black Salamander', 40, 'w'),
  Task('Complete the Easy Wilderness Diary', 40, 'w'),
  Task('Complete the Medium Wilderness Diary', 40, 'w'),
  Task('Complete the Wilderness Agility Course', 40, 'w'),
  Task('Defeat a Green Dragon in the Wilderness', 40, 'w'),
  Task('Defeat a Lava Dragon in the Wilderness', 40, 'w'),
  Task('Defeat the Chaos Fanatic', 40, 'w'),
  Task('Defeat the Crazy Archaeologist', 40, 'w'),
  Task('Destroy the one ring to rule them all', 40, 'w'),
  Task('Enter the Deep Wilderness Dungeon', 40, 'w'),
  Task('Equip a Bracelet of Ethereum', 40, 'w'),
  Task('Equip a Fedora', 40, 'w'),
  Task('Equip a God Cape', 40, 'w'),
  Task('Obtain an Ecumenical Key', 40, 'w'),
  Task('Open 1 Muddy Chest', 40, 'w'),
  Task('Open 15 Larrans Chests', 40, 'w'),
  Task('Open a Looting Bag', 40, 'w'),
  Task('Open One of Larrans Chests', 40, 'w'),
  Task('Sacrifice Some Bones at the Chaos Temple', 40, 'w'),
  Task('Use the Abyss', 40, 'w'),
  Task('1 Master Clue Scroll', 80),
  Task('100 Collection log slots', 80),
  Task('100 Combat Achievement Points', 80),
  Task('150 Elite Clue Scrolls', 80),
  Task('150 Hard Clue Scrolls', 80),
  Task('25 Combat Achievement Points', 80),
  Task('25 Combat Achievements', 80),
  Task('25 Elite Clue Scrolls', 80),
  Task('25 Master Clue Scrolls', 80),
  Task('50 Collection log slots', 80),
  Task('50 Combat Achievement Points', 80),
  Task('50 Combat Achievements', 80),
  Task('75 Elite Clue Scrolls', 80),
  Task('75 Hard Clue Scrolls', 80),
  Task('Achieve Your First Level 60', 80),
  Task('Achieve Your First Level 70', 80),
  Task('Achieve Your First Level 80', 80),
  Task('Build a Marble Lectern', 80, '**fixme**'),
  Task('Build an Achievement Gallery', 80),
  Task('Burn 100 Yew Logs', 80),
  Task('Burn Some Magic Logs', 80),
  Task('Cast a Surge Spell', 80, '**fixme**'),
  Task('Cast a Wave Spell', 80),
  Task('Catch 100 Shark', 80),
  Task('Catch a Dragon Impling', 80),
  Task('Check a grown Palm Tree', 80),
  Task('Chop 75 Magic Logs', 80),
  Task('Clean 100 Grimy Dwarf Weed', 80),
  Task('Complete 1 Speed Task', 80),
  Task('Complete 100 Mahogany homes contracts', 80, '**fixme**'),
  Task('Complete 100 Slayer Tasks', 80),
  Task('Complete 200 Mahogany homes contracts', 80, '**fixme**'),
  Task('Complete 250 Laps of a Rooftop Agility Course', 80),
  Task('Complete 5 Speed Tasks', 80),
  Task('Complete 50 Slayer Tasks', 80),
  Task('Complete a Mahogany homes expert contract', 80, '**fixme**'),
  Task('Complete the Hard Western Provinces Diary', 80, '**fixme**'),
  Task('Cook 100 pies.', 80),
  Task('Cook 100 Sharks', 80),
  Task('Cook 20 Redberry Pies.', 80),
  Task('Craft 2500 Essence Into Runes', 80),
  Task('Craft 30 Blue Dragonhide Bodies', 80),
  Task('Craft a Dragonstone Amulet', 80),
  Task('Create a black dhide shield', 80, '**fixme**'),
  Task('Defeat 10 Superior Slayer Creatures', 80),
  Task('Defeat 20 Superior Slayer Creatures', 80),
  Task('Defeat a Slayer Boss', 80, '**fixme**'),
  Task('Dig Up Some Magic Roots', 80),
  Task('Equip a Combination Battlestaff or Mystic Staff', 80),
  Task('Equip a Dragon Weapon', 80),
  Task('Equip a Full Black Dragonhide Set', 80),
  Task('Equip a Full Gilded or Trimmed Wizard Set', 80),
  Task('Equip a Full Gilded Set', 80),
  Task('Equip a Full God Dragonhide Set', 80),
  Task('Equip a Full God Rune Set', 80),
  Task('Equip a Full Vestment Set', 80),
  Task('Equip a Magic Shortbow', 80),
  Task('Equip a Mist Battlestaff', 80),
  Task('Equip a Rune Crossbow', 80),
  Task('Equip a two-handed Axe.', 80),
  Task('Equip an Ornament Kit Item', 80),
  Task('Equip Some Ranger Boots', 80),
  Task('Fill 10 Beginner Clue Collection Log Slots', 80),
  Task('Fill 10 Elite Clue Collection Log Slots', 80),
  Task('Fill 15 Hard Clue Collection Log Slots', 80),
  Task('Fill 20 Easy Clue Collection Log Slots', 80),
  Task('Fill 20 Medium Clue Collection Log Slots', 80),
  Task('Fill 5 Master Clue Collection Log Slots', 80),
  Task('Fill a Giant Pouch', 80),
  Task('Fill a Hard S.T.A.S.H. Unit', 80),
  Task('Fletch 200 Magic Longbow (u)', 80),
  Task('Fletch a Magic Shield', 80),
  Task('Fletch a Magic Shortbow', 80),
  Task('Fletch a Rune Crossbow', 80),
  Task('Gain 10 Unique Items From Elite Clues', 80),
  Task('Gain 10 Unique Items From Master Clues', 80),
  Task('Gain 20 Unique Items From Hard Clues', 80),
  Task('Gain 25 Unique Items From Medium Clues', 80),
  Task('Gain 35 Unique Items From Beginner Clues', 80),
  Task('Gain 35 Unique Items From Easy Clues', 80),
  Task('Gain a Unique Item From a Master Clue', 80),
  Task('Gain a Unique Item From an Elite Clue', 80),
  Task('Make 20 Ranging Potions', 80),
  Task('Make a Saradomin Brew', 80),
  Task('Mine 50 Adamantite Ore', 80),
  Task('Mine a shooting star', 80),
  Task('Obtain a Magic seed from a birds nest', 80),
  Task('Reach a Prayer Bonus of 30', 80),
  Task('Reach Base Level 60', 80),
  Task('Reach Base Level 70', 80),
  Task('Reach Combat Level 100', 80),
  Task('Reach Combat Level 110', 80),
  Task('Reach Total Level 1500', 80),
  Task('Reach Total Level 1750', 80),
  Task('Restore 75 Prayer Points at an Altar', 80),
  Task('Smelt a Runite Bar', 80),
  Task('Smith a Rune Item', 80),
  Task('Steal From a Gem Stall', 80),
  Task('Complete a Game of Veteran Pest Control', 80, 'a'),
  Task('Complete Land of the Goblins', 80, '**fixme**'),
  Task('Complete the Hard Falador Diary', 80, 'a'),
  Task('Craft 50 Law Runes', 80, 'a'),
  Task('Defeat Any God Wars Dungeon Boss 100 Times', 80, 'a'),
  Task('Defeat Any God Wars Dungeon Boss 250 Times', 80, 'a'),
  Task('Defeat Cerberus 150 times', 80, 'a'),
  Task('Defeat Cerberus 50 times', 80, 'a'),
  Task('Defeat Cerberus', 80, 'a'),
  Task('Defeat Commander Zilyana', 80, 'a'),
  Task('Defeat General Graardor', 80, 'a'),
  Task('Defeat Kril Tsutsaroth', 80, 'a'),
  Task('Defeat Kreearra', 80, 'a'),
  Task('Defeat Nex 150 Times', 80, 'a'),
  Task('Defeat Nex 50 Times', 80, 'a'),
  Task('Defeat Nex', 80, 'a'),
  Task('Defeat the Giant Mole 300 Times', 80, 'a'),
  Task('Defeat Whisperer 150 times', 80, '**fixme**'),
  Task('Defeat Whisperer 50 times', 80, '**fixme**'),
  Task('Defeat Whisperer', 80, '**fixme**'),
  Task('Equip a Dragon Defender', 80, 'a'),
  Task('Equip a Full Prospector Outfit', 80, 'a'),
  Task('Equip a Full Rogue Outfit', 80, 'a'),
  Task('Equip a Full Void Knight Set', 80, 'a'),
  Task('Equip a Pair of Dragon Boots', 80, 'a'),
  Task('Equip a Piece of the Golden Prospector set', 80, 'a'),
  Task('Equip a Saradomin Sword', 80, 'a'),
  Task('Equip some Zaryte Vambraces', 80, 'a'),
  Task('Keep the Veteran Void Knight Above 150 Hitpoints', 80, 'a'),
  Task('Purchase a Celestial ring', 80, 'a'),
  Task('Steal a Diamond in Dorgesh-Kaan', 80, 'a'),
  Task('The Frozen Door', 80, 'a'),
  Task('100 Tempoross Kills', 80, 'd'),
  Task('200 Tempoross Kills', 80, 'd'),
  Task('Cast Ice Blitz', 80, 'd'),
  Task('Cast Ice Burst', 80, 'd'),
  Task('Cast Paddewwa Teleport', 80, 'd'),
  Task('Check a grown Potato Cactus', 80, 'd'),
  Task('Commune a Pharaohs Sceptre to the Necropolis', 80, 'd'),
  Task('Complete Beneath Cursed Sands', 80, 'd'),
  Task('Complete the Hard Desert Diary', 80, 'd'),
  Task('Complete Tombs of Amascut 50 times', 80, 'd'),
  Task('Complete Tombs of Amascut', 80, 'd'),
  Task('Create the Colossal Rune Pouch', 80, 'd'),
  Task('Defeat Leviathan 150 times', 80, 'd'),
  Task('Defeat Leviathan 50 times', 80, 'd'),
  Task('Defeat the Kalphite Queen 50 Times', 80, 'd'),
  Task('Defeat the Kalphite Queen 150 Times', 80, 'd'),
  Task('Defeat the Kalphite Queen', 80, 'd'),
  Task('Defeat the Leviathan', 80, 'd'),
  Task('Equip a Dragon 2-Handed Sword', 80, 'd'),
  Task('Equip a full set of the Smiths outfit', 80, 'd'),
  Task('Equip a Mages Book', 80, 'd'),
  Task('Equip a Master Wand', 80, 'd'),
  Task('Equip the Abyssal Lantern', 80, 'd'),
  Task('Equip the Lightbearer', 80, 'd'),
  Task('Giants Foundry 100 hand-ins', 80, 'd'),
  Task('Giants Foundry 150 quality sword', 80, 'd'),
  Task('Giants Foundry 50 hand-ins', 80, 'd'),
  Task('Guardians of the Rift 100 Rifts closed', 80, 'd'),
  Task('Guardians of the Rift 50 Rifts closed', 80, 'd'),
  Task('Have Zahur Make 1,000 Unfinished Potions', 80, '**fixme**'),
  Task('Make 20 Magic Potions', 80, 'd'),
  Task('Make 50 Menaphite Remedies', 80, 'd'),
  Task('Obtain the Fish Barrel', 80, 'd'),
  Task('Pick a Summer Sqirk', 80, 'd'),
  Task('Pickpocket a Menaphite Thug 50 Times', 80, 'd'),
  Task('Room 7 of Pyramid Plunder', 80, 'd'),
  Task('Room 8 of Pyramid Plunder 25 Times', 80, 'd'),
  Task('Room 8 of Pyramid Plunder', 80, 'd'),
  Task('Smith 1,000 Adamant Dart Tips', 80, 'd'),
  Task('Turn in 25 Autumn Sqirkjuices to Osman', 80, 'd'),
  Task('Build a Gilded Altar', 80, 'f'),
  Task('Cast Fertile Soil', 80, 'f'),
  Task('Collect Miscellania Resources at Full Approval', 80, 'f'),
  Task('Complete the Hard Fremennik Diary', 80, 'f'),
  Task('Complete the Rellekka Agility Course', 80, 'f'),
  Task('Defeat a Rune Dragon', 80, 'f'),
  Task('Defeat Duke Sucellus 150 times', 80, '**fixme**'),
  Task('Defeat Duke Sucellus 50 times', 80, '**fixme**'),
  Task('Defeat Duke Sucellus', 80, '**fixme**'),
  Task('Defeat Each Dagannoth King 150 Times', 80, 'f'),
  Task('Defeat Each Dagannoth King 50 Times', 80, 'f'),
  Task('Defeat Phantom Muspah 150 times', 80, 'f'),
  Task('Defeat Phantom Muspah 50 times', 80, 'f'),
  Task('Defeat Phantom Muspah', 80, 'f'),
  Task('Defeat the Dagannoth Kings Without Leaving', 80, 'f'),
  Task('Defeat Vorkath 150 Times', 80, 'f'),
  Task('Defeat Vorkath 50 Times', 80, 'f'),
  Task('Defeat Vorkath', 80, 'f'),
  Task('Equip a Berserker Ring', 80, 'f'),
  Task('Equip a Full Rockshell Armour Set', 80, 'f'),
  Task('Equip a Full Skeletal Armour Set', 80, 'f'),
  Task('Equip a Full Spined Armour Set', 80, 'f'),
  Task('Equip a Leaf-Bladed Battleaxe', 80, 'f'),
  Task('Equip a Mud Battlestaff', 80, 'f'),
  Task('Equip a Seers Ring', 80, 'f'),
  Task('Equip a Seercull', 80, 'f'),
  Task('Equip a Warrior Ring', 80, 'f'),
  Task('Equip an Archers Ring', 80, 'f'),
  Task('Equip an Avas Assembler', 80, 'f'),
  Task('Equip the Ancient Sceptre', 80, '**fixme**'),
  Task('Harvest a Snapdragon in Weiss', 80, 'f'),
  Task('Trap a Sabre-toothed Kyatt', 80, 'f'),
  Task('Use the Special Attack of a Dragon Axe', 80, 'f'),
  Task('Use Your Portal Nexus to Teleport to Weiss', 80, 'f'),
  Task('Complete Path of Glouphrie', 80, 'k'),
  Task('Complete the Hard Ardougne Diary', 80, 'k'),
  Task('Complete the Hard Kandarin Diary', 80, 'k'),
  Task('Complete the Seers Village Agility Course', 80, 'k'),
  Task('Defeat 150 Demonic Gorillas', 80, 'k'),
  Task('Defeat a Cave Kraken', 80, 'k'),
  Task('Defeat a Demonic Gorilla', 80, 'k'),
  Task('Defeat a Smoke Devil', 80, 'k'),
  Task('Defeat the Kraken Boss 150 Times', 80, 'k'),
  Task('Defeat the Kraken Boss 50 Times', 80, 'k'),
  Task('Enter the Myths Guild', 80, '**fixme**'),
  Task('Equip a Fighter Torso', 80, 'k'),
  Task('Equip a Full Anglers Outfit', 80, '**fixme**'),
  Task('Equip a Karamja Monkey Backpack', 80, 'k'),
  Task('Equip a Trident of the Seas', 80, 'k'),
  Task('Equip a Warped Sceptre', 80, 'k'),
  Task('Equip an Ogre Expert Chompy Hat', 80, 'k'),
  Task('Feed Longramble', 80, 'k'),
  Task('Fletch 100 Maple Longbow (u) in Kandarin', 80, 'k'),
  Task('Kill a Frogeel', 80, 'k'),
  Task('Kill a Jubster', 80, 'k'),
  Task('Pickpocket a Hero', 80, 'k'),
  Task('Reach Level 5 in Any Barbarian Assault Role', 80, 'k'),
  Task('Use the Piety Prayer', 80, 'k'),
  Task('Check a grown Calquat Tree', 80),
  Task('Complete the Hard Karamja Diary', 80),
  Task('Complete Tzhaar-Ket-Raks first challenge', 80),
  Task('Complete Tzhaar-Ket-Raks second challenge', 80),
  Task('Cook 20 Karambwans in a row', 80),
  Task('Equip a Full Obsidian Armour Set', 80),
  Task('Equip a Red Topaz Machete', 80),
  Task('Equip a Toktz-Ket-Xil', 80),
  Task('Equip a Toktz-Xil-Ak', 80),
  Task('Equip a Toktz-Xil-Ek', 80),
  Task('Equip a TzHaar-Ket-Om', 80),
  Task('Equip an Obsidian Cape', 80),
  Task('Equip Some Dragon Platelegs or a Dragon Plateskirt', 80),
  Task('Find a Gout Tuber', 80),
  Task('Receive 30 Agility Arena Tickets With No Mistakes', 80),
  Task('Survive a Hit From TzTok-Jad Without Prayer', 80),
  Task('Take a Shortcut Across the Shilo Village River', 80),
  Task('1 Alchemical Hydra Kill', 80, 'z'),
  Task('1 Chambers of Xeric', 80, 'z'),
  Task('1 Mimic Kill', 80, 'z'),
  Task('1 Skotizo Kill', 80, 'z'),
  Task('10 Skotizo Kills', 80, 'z'),
  Task('100 Wintertodt Kills', 80, 'z'),
  Task('150 Alchemical Hydra Kills', 80, 'z'),
  Task('150 Chambers of Xeric', 80, 'z'),
  Task('150 Sarachnis Kills', 80, 'z'),
  Task('200 Wintertodt Kills', 80, 'z'),
  Task('25 Skotizo Kills', 80, 'z'),
  Task('300 Sarachnis Kills', 80, 'z'),
  Task('5 Mimic Kills', 80, 'z'),
  Task('50 Alchemical Hydra Kills', 80, 'z'),
  Task('50 Chambers of Xeric', 80, 'z'),
  Task('750 Lizardmen Shaman Kills', 80, 'z'),
  Task('Activate an Arcane or Dexterous Prayer Scroll', 80, 'z'),
  Task('Cast Full Sinister Offering', 80, '**fixme**'),
  Task('Chop 200 Redwood Logs', 80, 'z'),
  Task('Complete 150 Farming Contracts', 80, 'z'),
  Task('Complete 50 Farming Contracts', 80, 'z'),
  Task('Defeat a Hydra', 80, 'z'),
  Task('Defeat Vardorvis 150 times', 80, '**fixme**'),
  Task('Defeat Vardorvis 50 times', 80, '**fixme**'),
  Task('Defeat Vardorvis', 80, '**fixme**'),
  Task('Enter the Farming Guilds High Tier', 80, 'z'),
  Task('Equip a Brimstone Ring', 80, 'z'),
  Task('Equip a Dust Battlestaff', 80, 'z'),
  Task('Equip a Pearl Barbarian Rod', 80, '**fixme**'),
  Task('Equip a Pearl Fishing Rod', 80, 'z'),
  Task('Equip a Sarachnis Cudgel', 80, 'z'),
  Task('Equip Boots of Brimstone', 80, 'z'),
  Task('Equip Ferocious Gloves', 80, '**fixme**'),
  Task('Equip the Farmers Outfit', 80, 'z'),
  Task('Equip the Pyromancers Garb', 80, 'z'),
  Task('Fletch a Redwood Shield', 80, 'z'),
  Task('Friend of House Lovakengj', 80, 'z'),
  Task('Kourend and Kebos Hard Diary Tasks', 80, 'z'),
  Task('Plant 100 Bologano Seeds', 80, 'z'),
  Task('Plant 100 Logavano Seeds', 80, 'z'),
  Task('Plant an Anima Seed', 80, 'z'),
  Task('Catch 200 Implings in Puro-Puro', 80),
  Task('Catch a Herbiboar 50 Times', 80),
  Task('Check a grown Magic Tree in Lumbridge', 80),
  Task('Check a grown Mahogany Tree', 80),
  Task('Complete the Hard Lumbridge & Draynor Diary', 80),
  Task('Complete the Hard Varrock Diary', 80),
  Task('Defeat the Abyssal Sire', 80),
  Task('Equip a Hill Giant Club', 80),
  Task('Equip Bryophytas Staff', 80),
  Task('Offer an Unsired to the Font of Consumption', 80),
  Task('Purchase an Ectoplasmator', 80),
  Task('Set up a Magic Bird House', 80),
  Task('Take the Advanced Shortcut to the Cosmic Altar', 80),
  Task('Try and feed a stray dog something exotic', 80),
  Task('Burn 20 Blisterwood Logs', 80, 'm'),
  Task('Complete a Hard Temple Trek', 80, 'm'),
  Task('Complete Sins of the Father', 80, 'm'),
  Task('Complete the Hard Morytania Diary', 80, 'm'),
  Task('Complete the Theatre of Blood With No Deaths', 80, 'm'),
  Task('Create the long rope shortcut in Darkmeyer', 80, 'm'),
  Task('Defeat a Urium Shade', 80, 'm'),
  Task('Defeat Phosanis Nightmare', 80, 'm'),
  Task('Defeat the Grotesque Guardians 150 Times', 80, 'm'),
  Task('Defeat the Grotesque Guardians 50 Times', 80, 'm'),
  Task('Defeat the Grotesque Guardians', 80, 'm'),
  Task('Defeat The Nightmare 50 times', 80, 'm'),
  Task('Defeat The Nightmare', 80, 'm'),
  Task('Equip a Full set of Swampbark armour', 80, 'm'),
  Task('Equip a Full Set of Zealots Robes', 80, 'm'),
  Task('Equip a Granite Hammer or Granite Ring', 80, 'm'),
  Task('Equip a Piece of Zealots Robes', 80, 'm'),
  Task('Equip any Full Barrows Armour Set', 80, 'm'),
  Task('Equip Full Ahrims Armour Set', 80, 'm'),
  Task('Equip Full Dharoks Armour Set', 80, 'm'),
  Task('Equip Full Guthans Armour Set', 80, 'm'),
  Task('Equip Full Karils Armour Set', 80, 'm'),
  Task('Equip Full Torags Armour Set', 80, 'm'),
  Task('Equip Full Veracs Armour Set', 80, 'm'),
  Task('Floor 3 of the Hallowed Sepulchre', 80, 'm'),
  Task('Floor 4 of the Hallowed Sepulchre', 80, 'm'),
  Task('Obtain Every Hallowed Tool', 80, 'm'),
  Task('Open a Gold Chest', 80, 'm'),
  Task('Pickpocket a Vyre 50 Times', 80, 'm'),
  Task('Purchase a Reward From the Hallowed Sepulchre', 80, 'm'),
  Task('Unlock permanent boat travel with Andras', 80, 'm'),
  Task('Catch a Crystal Impling', 80, 't'),
  Task('Check a grown Crystal Tree', 80, 't'),
  Task('Chop 100 Teak Logs in Prifddinas', 80, 't'),
  Task('Complete 50 laps of the Prifddinas Agility Course', 80, 't'),
  Task('Complete the Corrupted Gauntlet', 80, 't'),
  Task('Complete the Prifddinas Agility Course in 1:10', 80, 't'),
  Task('Complete the Prifddinas Agility Course', 80, 't'),
  Task('Craft a Piece of Crystal Armour', 80, 't'),
  Task('Craft an Eternal Teleport Crystal', 80, 't'),
  Task('Defeat a Dark Beast in Tirannwn', 80, 't'),
  Task('Defeat a Nechryael in Tirannwn', 80, 't'),
  Task('Defeat Zalcano 50 Times', 80, 't'),
  Task('Defeat Zalcano', 80, 't'),
  Task('Defeat Zulrah 50 Times', 80, 't'),
  Task('Defeat Zulrah', 80, 't'),
  Task('Equip a Crystal Bow', 80, 't'),
  Task('Equip a Crystal Halberd', 80, '**fixme**'),
  Task('Equip a Crystal Shield', 80, 't'),
  Task('Equip a Dark Bow in Tirannwn', 80, 't'),
  Task('Equip any piece of Crystal Armour', 80, 't'),
  Task('Find Every Memoriam Crystal', 80, 't'),
  Task('Kill 50 Elves in Tirannwn', 80, 't'),
  Task('Make 50 Teak Planks in Prifddinas', 80, 't'),
  Task('Mine 200 Soft Clay in Tirannwn', 80, 't'),
  Task('Open the Enhanced Crystal Chest', 80, 't'),
  Task('Pickpocket an Elf 50 Times', 80, 't'),
  Task('Receive a Dragonstone Amulet from an Impling', 80, 't'),
  Task('Use a prayer altar to restore 90 prayer in Prifddinas', 80, 't'),
  Task('Catch 100 Dark Crabs', 80, 'w'),
  Task('Complete the Hard Wilderness Diary', 80, 'w'),
  Task('Craft an Air Battlestaff in the Wilderness', 80, 'w'),
  Task('Defeat Callisto 150 times', 80, 'w'),
  Task('Defeat Callisto 50 times', 80, 'w'),
  Task('Defeat Callisto', 80, 'w'),
  Task('Defeat Scorpia', 80, 'w'),
  Task('Defeat the Chaos Elemental', 80, 'w'),
  Task('Defeat the Corporeal Beast 50 Times', 80, 'w'),
  Task('Defeat the Corporeal Beast', 80, 'w'),
  Task('Defeat the King Black Dragon', 80, 'w'),
  Task('Defeat Venenatis 150 times', 80, 'w'),
  Task('Defeat Venenatis 50 times', 80, 'w'),
  Task('Defeat Venenatis', 80, 'w'),
  Task('Defeat Vetion 150 times', 80, 'w'),
  Task('Defeat Vetion 50 times', 80, 'w'),
  Task('Defeat Vetion', 80, 'w'),
  Task('Equip 100 Black Chinchompas', 80, 'w'),
  Task('Equip a Dragon 2-Handed Sword in the Wilderness', 80, 'w'),
  Task('Equip a Dragon Pickaxe', 80, 'w'),
  Task('Equip an Enchanted Slayer Staff', 80, 'w'),
  Task('Imbue a God Cape', 80, 'w'),
  Task('Loot a dragonstone from the Rogues Castle', 80, 'w'),
  Task('Open 10 Muddy Chests', 80, 'w'),
  Task('Open 50 Larrans Chests', 80, 'w'),
  Task('Sacrifice Some Dragon Bones at the Chaos Temple', 80, 'w'),
  Task('100 Combat Achievements', 200),
  Task('1000 Combat Achievement Points', 200),
  Task('150 Combat Achievements', 200),
  Task('150 Master Clue Scrolls', 200),
  Task('200 Collection log slots', 200),
  Task('200 Combat Achievement Points', 200),
  Task('200 Combat Achievements', 200),
  Task('250 Combat Achievements', 200),
  Task('300 Combat Achievement Points', 200),
  Task('300 Combat Achievements', 200),
  Task('350 Collection log slots', 200),
  Task('400 Combat Achievement Points', 200),
  Task('500 Collection log slots', 200),
  Task('500 Combat Achievement Points', 200),
  Task('600 Combat Achievement Points', 200),
  Task('700 Combat Achievement Points', 200),
  Task('75 Master Clue Scrolls', 200),
  Task('800 Combat Achievement Points', 200),
  Task('900 Combat Achievement Points', 200),
  Task('Achieve Your First Level 90', 200),
  Task('Achieve Your First Level 95', 200),
  Task('Activate an Imbued Heart', 200),
  Task('Add a Jar to a Display Case', 200),
  Task('Blow 100 Light Orbs', 200),
  Task('Build a Spirit tree & fairy ring.', 200),
  Task('Catch a Lucky Impling Bare-Handed', 200),
  Task('Combat Achievements Easy Tier', 200),
  Task('Combat Achievements Medium Tier', 200),
  Task('Complete 10 Speed Tasks', 200),
  Task('Complete 20 Speed Tasks', 200),
  Task('Complete 200 Slayer Tasks', 200),
  Task('Complete 30 Speed Tasks', 200),
  Task('Complete the Elite Western Provinces Diary', 200, '**fixme**'),
  Task('Craft an Onyx Amulet', 200),
  Task('Defeat 50 Superior Slayer Creatures', 200),
  Task('Equip a Full Dragon Set', 200, '**fixme**'),
  Task('Equip a Heavy Casket', 200),
  Task('Equip a piece of Virtus', 200, '**fixme**'),
  Task('Equip a Scroll Sack', 200),
  Task('Equip an Abyssal Whip', 200),
  Task('Equip an Eternal Slayer Ring', 200),
  Task('Equip an Infernal Tool', 200, '**fixme**'),
  Task('Equip the Mask of Rebirth', 200, '**fixme**'),
  Task('Equip the Soulreaper Axe', 200, '**fixme**'),
  Task('Fill 25 Elite Clue Collection Log Slots', 200),
  Task('Fill 25 Master Clue Collection Log Slots', 200),
  Task('Fill 30 Hard Clue Collection Log Slots', 200),
  Task('Fill 40 Medium Clue Collection Log Slots', 200),
  Task('Fill 50 Easy Clue Collection Log Slots', 200),
  Task('Fill Every Beginner Clue Collection Log Slot', 200),
  Task('Fletch 100 Dragon Javelins', 200),
  Task('Gain 25 Unique Items From Elite Clues', 200),
  Task('Gain 25 Unique Items From Master Clues', 200),
  Task('Gain 50 Unique Items From Hard Clues', 200),
  Task('Make a Super Combat Potion', 200),
  Task('Obtain 25 Million Agility XP', 200),
  Task('Obtain 25 Million Attack XP', 200),
  Task('Obtain 25 Million Construction XP', 200),
  Task('Obtain 25 Million Cooking XP', 200),
  Task('Obtain 25 Million Crafting XP', 200),
  Task('Obtain 25 Million Defence XP', 200),
  Task('Obtain 25 Million Farming XP', 200),
  Task('Obtain 25 Million Firemaking XP', 200),
  Task('Obtain 25 Million Fishing XP', 200),
  Task('Obtain 25 Million Fletching XP', 200),
  Task('Obtain 25 Million Herblore XP', 200),
  Task('Obtain 25 Million Hitpoints XP', 200),
  Task('Obtain 25 Million Hunter XP', 200),
  Task('Obtain 25 Million Magic XP', 200),
  Task('Obtain 25 Million Mining XP', 200),
  Task('Obtain 25 Million Prayer XP', 200),
  Task('Obtain 25 Million Ranged XP', 200),
  Task('Obtain 25 Million Runecraft XP', 200),
  Task('Obtain 25 Million Slayer XP', 200),
  Task('Obtain 25 Million Smithing XP', 200),
  Task('Obtain 25 Million Strength XP', 200),
  Task('Obtain 25 Million Thieving XP', 200),
  Task('Obtain 25 Million Woodcutting XP', 200),
  Task('Obtain 35 Million Agility XP', 200),
  Task('Obtain 35 Million Attack XP', 200),
  Task('Obtain 35 Million Construction XP', 200),
  Task('Obtain 35 Million Cooking XP', 200),
  Task('Obtain 35 Million Crafting XP', 200),
  Task('Obtain 35 Million Defence XP', 200),
  Task('Obtain 35 Million Farming XP', 200),
  Task('Obtain 35 Million Firemaking XP', 200),
  Task('Obtain 35 Million Fishing XP', 200),
  Task('Obtain 35 Million Fletching XP', 200),
  Task('Obtain 35 Million Herblore XP', 200),
  Task('Obtain 35 Million Hitpoints XP', 200),
  Task('Obtain 35 Million Hunter XP', 200),
  Task('Obtain 35 Million Magic XP', 200),
  Task('Obtain 35 Million Mining XP', 200),
  Task('Obtain 35 Million Prayer XP', 200),
  Task('Obtain 35 Million Ranged XP', 200),
  Task('Obtain 35 Million Runecraft XP', 200),
  Task('Obtain 35 Million Slayer XP', 200),
  Task('Obtain 35 Million Smithing XP', 200),
  Task('Obtain 35 Million Strength XP', 200),
  Task('Obtain 35 Million Thieving XP', 200),
  Task('Obtain 35 Million Woodcutting XP', 200),
  Task('Obtain 50 Million Agility XP', 200),
  Task('Obtain 50 Million Attack XP', 200),
  Task('Obtain 50 Million Construction XP', 200),
  Task('Obtain 50 Million Cooking XP', 200),
  Task('Obtain 50 Million Crafting XP', 200),
  Task('Obtain 50 Million Defence XP', 200),
  Task('Obtain 50 Million Farming XP', 200),
  Task('Obtain 50 Million Firemaking XP', 200),
  Task('Obtain 50 Million Fishing XP', 200),
  Task('Obtain 50 Million Fletching XP', 200),
  Task('Obtain 50 Million Herblore XP', 200),
  Task('Obtain 50 Million Hitpoints XP', 200),
  Task('Obtain 50 Million Hunter XP', 200),
  Task('Obtain 50 Million Magic XP', 200),
  Task('Obtain 50 Million Mining XP', 200),
  Task('Obtain 50 Million Prayer XP', 200),
  Task('Obtain 50 Million Ranged XP', 200),
  Task('Obtain 50 Million Runecraft XP', 200),
  Task('Obtain 50 Million Slayer XP', 200),
  Task('Obtain 50 Million Smithing XP', 200),
  Task('Obtain 50 Million Strength XP', 200),
  Task('Obtain 50 Million Thieving XP', 200),
  Task('Obtain 50 Million Woodcutting XP', 200),
  Task('Obtain a Boss Pet', 200),
  Task('Obtain a Skilling Pet', 200),
  Task('Reach Base Level 80', 200),
  Task('Reach Base Level 90', 200),
  Task('Reach Combat Level 120', 200),
  Task('Reach Combat Level 126', 200),
  Task('Reach Level 99 Agility', 200),
  Task('Reach Level 99 Attack', 200),
  Task('Reach Level 99 Construction', 200),
  Task('Reach Level 99 Cooking', 200),
  Task('Reach Level 99 Crafting', 200),
  Task('Reach Level 99 Defence', 200),
  Task('Reach Level 99 Farming', 200),
  Task('Reach Level 99 Firemaking', 200),
  Task('Reach Level 99 Fishing', 200),
  Task('Reach Level 99 Fletching', 200),
  Task('Reach Level 99 Herblore', 200),
  Task('Reach Level 99 Hitpoints', 200),
  Task('Reach Level 99 Hunter', 200),
  Task('Reach Level 99 Magic', 200),
  Task('Reach Level 99 Mining', 200),
  Task('Reach Level 99 Prayer', 200),
  Task('Reach Level 99 Ranged', 200),
  Task('Reach Level 99 Runecraft', 200),
  Task('Reach Level 99 Slayer', 200),
  Task('Reach Level 99 Smithing', 200),
  Task('Reach Level 99 Strength', 200),
  Task('Reach Level 99 Thieving', 200),
  Task('Reach Level 99 Woodcutting', 200),
  Task('Reach Total Level 2000', 200),
  Task('Reach Total Level 2100', 200),
  Task('Reach Total Level 2200', 200),
  Task('Read a Clueless Scroll', 200),
  Task('Slay an Abyssal Demon', 200),
  Task('Smith a Dragonfire Shield', 200),
  Task('Transform into Uri', 200),
  Task('Travel Between Your Spirit Trees', 200, '**fixme**'),
  Task('Use the Explore Emote', 200),
  Task('Complete the Elite Falador Diary', 200, 'a'),
  Task('Defeat Any God Wars Dungeon Boss 500 Times', 200, 'a'),
  Task('Defeat Awakened Whisperer', 200, '**fixme**'),
  Task('Defeat Cerberus 300 times', 200, 'a'),
  Task('Defeat Cerberus Before She Summons Souls', 200, 'a'),
  Task('Defeat Nex 300 Times', 200, 'a'),
  Task('Defeat Whisperer 300 times', 200, '**fixme**'),
  Task('Equip a Full Armadyl Armour Set', 200, 'a'),
  Task('Equip a Full Bandos Armour Set', 200, 'a'),
  Task('Equip a Full Graceful Outfit', 200, 'a'),
  Task('Equip a Full set of Golden Prospector', 200, 'a'),
  Task('Equip a full set of the Carpenters Outfit', 200, 'a'),
  Task('Equip a Godsword', 200, 'a'),
  Task('Equip a Piece of the Armadyl Armour Set', 200, 'a'),
  Task('Equip a Piece of the Bandos Armour Set', 200, 'a'),
  Task('Equip a Piece of Torva Armour', 200, 'a'),
  Task('Equip a Staff of the Dead', 200, 'a'),
  Task('Equip a Zamorakian Spear', 200, 'a'),
  Task('Equip a Zaryte Crossbow', 200, 'a'),
  Task('Equip an Armadyl Crossbow', 200, 'a'),
  Task('Equip Some Primordial, Pegasian or Eternal Boots', 200, '**fixme**'),
  Task('Equip the Bellator Ring', 200, '**fixme**'),
  Task('Cast Ice Barrage', 200, 'd'),
  Task('Complete the Elite Desert Diary', 200, 'd'),
  Task('Complete Tombs of Amascut 150 times', 200, 'd'),
  Task('Complete Tombs of Amascut 250 times', 200, 'd'),
  Task('Craft a Ghorrock Teleport Tablet', 200, 'd'),
  Task('Defeat Awakened Leviathan', 200, 'd'),
  Task('Defeat Leviathan 300 times', 200, 'd'),
  Task('Equip a Dragon Chainbody in the Kharidian Desert', 200, 'd'),
  Task('Equip a full set of Raiment of the eye', 200, 'd'),
  Task('Equip a Piece of Masori Armour', 200, 'd'),
  Task('Equip a Piece of the Infinity Robe Set', 200, 'd'),
  Task('Equip Masori Assembler', 200, '**fixme**'),
  Task('Equip Osmumtens Fang', 200, 'd'),
  Task('Equip the Elidinis Ward (Or)', 200, '**fixme**'),
  Task('Equip the Elidinis Ward', 200, 'd'),
  Task('Fletch 200 Dragon Darts', 200, 'd'),
  Task('Hit 150 with the Keris Partisan', 200, 'd'),
  Task('Room 8 of Pyramid Plunder 150 Times', 200, 'd'),
  Task('Room 8 of Pyramid Plunder 75 Times', 200, 'd'),
  Task('Smith 1,000 Rune Dart Tips', 200, 'd'),
  Task('Turn in 50 Summer Sqirkjuices to Osman', 200, 'd'),
  Task('Build a Gilded Portal Nexus', 200, 'f'),
  Task('Build a Gold Sink', 200, 'f'),
  Task('Cast Spellbook Swap', 200, 'f'),
  Task('Complete the Elite Fremennik Diary', 200, 'f'),
  Task('Create a Catherby Teleport Tablet', 200, 'f'),
  Task('Create the Saturated Heart', 200, 'f'),
  Task('Dagannoth Kings Combat Achievements', 200, 'f'),
  Task('Defeat Awakened Duke Sucellus', 200, '**fixme**'),
  Task('Defeat Duke Sucellus 300 times', 200, '**fixme**'),
  Task('Defeat Each Dagannoth King 300 Times', 200, 'f'),
  Task('Defeat Phantom Muspah 300 times', 200, 'f'),
  Task('Defeat Vorkath 15 Times Without Leaving', 200, 'f'),
  Task('Defeat Vorkath 300 Times', 200, 'f'),
  Task('Defeat Vorkath 5 Times Without Special Damage', 200, 'f'),
  Task('Equip a Bonecrusher necklace', 200, '**fixme**'),
  Task('Equip a Completed God Book', 200, 'f'),
  Task('Equip a Dragon Crossbow', 200, 'f'),
  Task('Equip a Dragonbone Necklace', 200, 'f'),
  Task('Equip a Dragonfire Ward', 200, 'f'),
  Task('Equip a Neitiznot Faceguard', 200, 'f'),
  Task('Equip Every Dagannoth King Ring', 200, 'f'),
  Task('Equip the Magus Ring', 200, '**fixme**'),
  Task('Equip the Venator Bow', 200, 'f'),
  Task('Make 50 Forgotten Brews', 200, 'f'),
  Task('Phantom Muspah Combat Achievements', 200, 'f'),
  Task('Vorkath Combat Achievements', 200, 'f'),
  Task('Catch 150 Red Chinchompas in Kandarin', 200, 'k'),
  Task('Check a grown Dragonfruit Tree in Catherby', 200, 'k'),
  Task('Complete the Ardougne Agility Course', 200, 'k'),
  Task('Complete the Elite Ardougne Diary', 200, 'k'),
  Task('Complete the Elite Kandarin Diary', 200, 'k'),
  Task('Craft a Wrath Rune', 200, '**fixme**'),
  Task('Defeat 300 Demonic Gorillas', 200, 'k'),
  Task('Defeat 500 Demonic Gorillas', 200, 'k'),
  Task('Defeat the Kraken Boss 300 Times', 200, 'k'),
  Task('Equip a Dragon Archer Chompy Hat', 200, 'k'),
  Task('Equip a Dragon Full Helm', 200, 'k'),
  Task('Equip a Gnome Scarf', 200, '**fixme**'),
  Task('Equip a Heavy Ballista', 200, 'k'),
  Task('Equip a Light Ballista', 200, 'k'),
  Task('Equip a Maniacal Monkey Backpack', 200, 'k'),
  Task('Equip an Abyssal Tentacle', 200, 'k'),
  Task('Equip an Expert Dragon Archer Chompy Hat', 200, 'k'),
  Task('Equip an Occult Necklace', 200, 'k'),
  Task('Equip Some Zenyte Jewelry', 200, 'k'),
  Task('Purchase a Halo from Castlewars', 200, 'k'),
  Task('Complete the Elite Karamja Diary', 200),
  Task('Complete the Fight Caves 10 Times', 200),
  Task('Complete the Fight Caves 15 Times', 200),
  Task('Complete the Fight Caves 5 Times', 200),
  Task('Complete the Inferno 10 Times', 200),
  Task('Complete the Inferno 5 Times', 200),
  Task('Complete Tzhaar-Ket-Raks fifth challenge', 200),
  Task('Complete Tzhaar-Ket-Raks fourth challenge', 200),
  Task('Complete Tzhaar-Ket-Raks sixth challenge', 200),
  Task('Complete Tzhaar-Ket-Raks third challenge', 200),
  Task('Equip a Fire Cape', 200),
  Task('Pickpocket a Diamond From a TzHaar', 200),
  Task('Purchase an Onyx in Mor Ul Rek', 200),
  Task('Sacrifice a Fire Cape to Access the Inferno', 200),
  Task('Trade 100 Agility Arena Tickets for XP', 200),
  Task('1 Chambers of Xeric Challenge Mode', 200, 'z'),
  Task('1500 Lizardmen Shaman Kills', 200, 'z'),
  Task('250 Chambers of Xeric', 200, 'z'),
  Task('300 Alchemical Hydra Kills', 200, 'z'),
  Task('50 Chambers of Xeric Challenge Mode', 200, 'z'),
  Task('Alchemical Hydra Combat Achievements', 200, 'z'),
  Task('Burn 200 Redwood Logs', 200, 'z'),
  Task('Check a grown Redwood Tree', 200, 'z'),
  Task('Chop 500 Redwood logs', 200, 'z'),
  Task('Complete A Kingdom Divided', 200, 'z'),
  Task('Cook 100 Anglerfish.', 200, 'z'),
  Task('Defeat Awakened Vardorvis', 200, '**fixme**'),
  Task('Defeat Vardorvis 300 times', 200, '**fixme**'),
  Task('Equip a Dragon Hunter Crossbow', 200, 'z'),
  Task('Equip a Dragon Hunter Lance', 200, '**fixme**'),
  Task('Equip a Dragon Warhammer', 200, 'z'),
  Task('Equip a Golden Tench', 200, 'z'),
  Task('Equip a Kodai Wand', 200, '**fixme**'),
  Task('Equip a pair of Dragon Claws', 200, 'z'),
  Task('Equip a Twisted Buckler', 200, 'z'),
  Task('Equip an Elder Maul', 200, 'z'),
  Task('Equip any Ancestral piece', 200, 'z'),
  Task('Equip Dinhs Bulwark', 200, 'z'),
  Task('Equip the Ultor Ring', 200, '**fixme**'),
  Task('Fletch 250 Redwood logs into arrow shafts', 200, 'z'),
  Task('Kourend and Kebos Elite Diary Tasks', 200, 'z'),
  Task('Recolour a piece of the Ancestral Robes', 200, 'z'),
  Task('Abyssal Sire Combat Achievements', 200),
  Task('Buy an Ash Covered Tome', 200),
  Task('Catch a Herbiboar 150 Times', 200),
  Task('Complete the Elite Lumbridge & Draynor Diary', 200),
  Task('Complete the Elite Varrock Diary', 200),
  Task('Defeat the Abyssal Sire 150 Times', 200),
  Task('Defeat the Abyssal Sire 300 Times', 200),
  Task('Defeat the Abyssal Sire 50 Times', 200),
  Task('Equip a Dragonfire Shield', 200),
  Task('Equip a full set of the Forestry Outfit', 200, '**fixme**'),
  Task('Equip an Abyssal Bludgeon', 200),
  Task('Equip an Abyssal Dagger', 200),
  Task('Equip an Ancient Wyvern Shield', 200),
  Task('Equip the Venator Ring', 200, '**fixme**'),
  Task('Mine a Runite Ore Fragment', 200),
  Task('Receive a Torstol From a Herbiboar', 200),
  Task('Attach a Holy ornament kit to the Scythe of Vitur', 200, 'm'),
  Task('Attach a Sanguine ornament kit to the Scythe', 200, 'm'),
  Task('Complete the Elite Morytania Diary', 200, 'm'),
  Task('Complete the Hallowed Sepulchre in 8:00', 200, 'm'),
  Task('Complete the Theatre of Blood 150 Times', 200, 'm'),
  Task('Complete the Theatre of Blood 250 Times', 200, 'm'),
  Task('Complete the Theatre of Blood 50 Times', 200, 'm'),
  Task('Create an Amulet of Blood Fury', 200, 'm'),
  Task('Defeat The Nightmare 150 times', 200, 'm'),
  Task('Defeat The Nightmare 250 times', 200, 'm'),
  Task('Defeat the Theatre of Blood Hardmode 50 times', 200, 'm'),
  Task('Defeat the Theatre of Blood Hardmode', 200, 'm'),
  Task('Equip a Full set of Bloodbark armour', 200, 'm'),
  Task('Equip a Ghrazi Rapier', 200, 'm'),
  Task('Equip a Nightmare Staff', 200, 'm'),
  Task('Equip a Piece of the Inquisitors Set', 200, 'm'),
  Task('Equip a Piece of the Justiciar Set', 200, 'm'),
  Task('Equip a Ring of Endurance', 200, 'm'),
  Task('Equip a Sanguinesti Staff', 200, 'm'),
  Task('Equip an Avernic Defender', 200, '**fixme**'),
  Task('Equip an Inquisitors Mace', 200, 'm'),
  Task('Equip Every Barrows Armour Set', 200, 'm'),
  Task('Equip Some Guardian Boots', 200, '**fixme**'),
  Task('Floor 5 of the Hallowed Sepulchre', 200, 'm'),
  Task('Grotesque Guardians Combat Achievements', 200, 'm'),
  Task('Phosanis Nightmare Combat Achievements', 200, 'm'),
  Task('The Nightmare Combat Achievements', 200, 'm'),
  Task('Catch 300 Red Chinchompas in Tirannwn', 200, 't'),
  Task('Complete the Corrupted Gauntlet 150 Times', 200, 't'),
  Task('Complete the Corrupted Gauntlet 50 Times', 200, 't'),
  Task('Craft a Celestial Signet', 200, '**fixme**'),
  Task('Craft a Toxic Blowpipe', 200, 't'),
  Task('Craft a Toxic Trident', 200, '**fixme**'),
  Task('Create 100 Divine Ranging Potions', 200, 't'),
  Task('Create 50 Divine Super Combat Potions', 200, 't'),
  Task('Defeat Zalcano 150 Times', 200, 't'),
  Task('Defeat Zalcano 300 Times', 200, 't'),
  Task('Defeat Zulrah 150 Times', 200, 't'),
  Task('Defeat Zulrah 300 Times', 200, 't'),
  Task('Dismantle a Zulrah scale unique', 200, 't'),
  Task('Dissect 50 Sacred Eels', 200, 't'),
  Task('Equip a Crystal Grail', 200, 't'),
  Task('Equip a Full Crystal Armour Set', 200, 't'),
  Task('Equip a Piece of the Dragonstone Armour Set', 200, 't'),
  Task('Equip a Serpentine Helm', 200, 't'),
  Task('Equip an Elven Signet', 200, 't'),
  Task('Equip an Enhanced Crystal Weapon', 200, 't'),
  Task('Load a blowpipe with Dragon Darts', 200, 't'),
  Task('Mine 200 Runite Ore in Tirannwn', 200, 't'),
  Task('Obtain a Crystal Tool Seed', 200, 't'),
  Task('Obtain a Zalcano Shard', 200, 't'),
  Task('Smith 500 Rune Dart Tips in Prifddinas', 200, '**fixme**'),
  Task('Zulrah Combat Achievements', 200, 't'),
  Task('Build an Obelisk', 200, '**fixme**'),
  Task('Complete the Elite Wilderness Diary', 200, 'w'),
  Task('Cook a Dark Crab', 200, 'w'),
  Task('Defeat Callisto 300 times', 200, 'w'),
  Task('Defeat the Corporeal Beast 150 Times', 200, 'w'),
  Task('Defeat the Corporeal Beast 250 Times', 200, 'w'),
  Task('Defeat Venenatis 300 times', 200, 'w'),
  Task('Defeat Vetion 300 times', 200, 'w'),
  Task('Equip 250 Black Chinchompas', 200, 'w'),
  Task('Equip 500 Black Chinchompas', 200, 'w'),
  Task('Equip a Blessed Spirit Shield', 200, 'w'),
  Task('Equip a Full DagonHai Set', 200, 'w'),
  Task('Equip a Malediction Ward', 200, 'w'),
  Task('Equip a Piece of the DagonHai Set', 200, 'w'),
  Task('Equip a Ring of the Gods', 200, 'w'),
  Task('Equip a Thammarons Sceptre', 200, 'w'),
  Task('Equip a Treasonous Ring', 200, 'w'),
  Task('Equip a Tyrannical Ring', 200, 'w'),
  Task('Equip an Odium Ward', 200, 'w'),
  Task('Equip Craws Bow', 200, 'w'),
  Task('Equip full Elder chaos robe', 200, 'w'),
  Task('Equip the Accursed Sceptre', 200, 'w'),
  Task('Equip the Ursine Chainmace', 200, 'w'),
  Task('Equip the Voidwaker', 200, 'w'),
  Task('Equip the Webweaver', 200, 'w'),
  Task('Equip Viggoras Chainmace', 200, 'w'),
  Task('Make an Extended Antifire Potion', 200, 'w'),
  Task('Mine Some Runite Ore in the Wilderness', 200, 'w'),
  Task('750 Collection log slots', 400),
  Task('Combat Achievements Elite Tier', 400),
  Task('Combat Achievements Hard Tier', 400),
  Task('Combat Achievements Master Tier', 400),
  Task('Equip a Dragon Platebody or Dragon Kiteshield', 400, '**fixme**'),
  Task('Equip full Virtus', 400, '**fixme**'),
  Task('Reach Base Level 95', 400),
  Task('Reach Total Level 2277', 400),
  Task('Equip a Full Set of Torva Armour', 400, 'a'),
  Task('Equip Every Godsword', 400, 'a'),
  Task('Godwars Dungeon Combat Achievements', 400, 'a'),
  Task('Equip a Full Infinity Robe Set', 400, 'd'),
  Task('Equip a full set of Masori (f)', 400, '**fixme**'),
  Task('Equip Osmumtens Fang (or)', 400, 'd'),
  Task('Equip the Tumekens Shadow', 400, 'd'),
  Task('Tombs of Amascut Combat Achievements', 400, 'd'),
  Task('Build a Demonic Throne', 400, 'f'),
  Task('Equip Every Completed God Book', 400, 'f'),
  Task('Equip Every Draconic Shield', 400, 'f'),
  Task('Enhance a Trident of the Seas', 400, 'k'),
  Task('Equip a Kruk Jr. Monkey Backpack', 400, 'k'),
  Task('Equip a Prince Awowogei Monkey Backpack', 400, 'k'),
  Task('Equip All Zenyte Jewelry', 400, 'k'),
  Task('Complete the Inferno 15 Times', 400),
  Task('Complete Tzhaar-Ket-Raks Special challenge', 400),
  Task('Equip an Infernal Cape', 400),
  Task('The Fight Caves Combat Achievements', 400),
  Task('The Inferno Combat Achievements', 400),
  Task('TzHaar-Ket-Raks Combat Achievements', 400),
  Task('Chambers of Xeric Combat Achievements', 400, 'z'),
  Task('Equip a full set of Ancestral', 400, 'z'),
  Task('Equip a Twisted Bow', 400, 'z'),
  Task('Complete the Hallowed Sepulchre in 6:30', 400, 'm'),
  Task('Equip a Full Inquisitors Set', 400, 'm'),
  Task('Equip a Full Justiciar Set', 400, 'm'),
  Task('Equip a Nightmare Staff With an Orb', 400, 'm'),
  Task('Equip a Scythe of Vitur', 400, 'm'),
  Task('Theatre of Blood Combat Achievements', 400, 'm'),
  Task('Equip a Corrupted Blade of Saeldor', 400, 't'),
  Task('Equip a Corrupted Bow of Faerdhinen', 400, 't'),
  Task('Equip a Crystal Crown', 400, 't'),
  Task('Gauntlet Combat Achievements', 400, 't'),
  Task('Equip a Spectral or Arcane Spirit Shield', 400, 'w'),
  Task('Equip an Amulet of Eternal Glory', 400, 'w'),
  Task('Equip an Elysian Spirit Shield', 400, '**fixme**'),
  Task('Obtain Every Revenant Weapon', 400, 'w'),
]