from classes import Task

starter_tasks = [
    Task('1 Easy Clue Scroll', '', 'Open a Reward casket for completing an easy clue scroll.', 10),
    Task('1 Medium Clue Scroll', '', 'Open a Reward casket for completing a medium clue scroll.', 10),
    Task('25 Easy Clue Scrolls', '', 'Open 25 Reward caskets for completing easy clue scrolls.', 10),
    Task('Achieve Your First Level Up', '', 'Level up any of your skills for the first time.', 10),
    Task('Achieve Your First Level 5', '', 'Reach level 5 in any skill (not including Agility, Hitpoints and Runecraft).', 10),
    Task('Achieve Your First Level 10', '', 'Reach level 10 in any skill (not including Agility and Hitpoints).', 10),
    Task('Achieve Your First Level 20', '', 'Reach level 20 in any skill.', 10),
    Task('Build a Room in Your Player Owned House', '', 'Build a room in your Player Owned House.', 10),
    Task('Burn Some Coloured Logs', '', 'Burn some logs that have been coloured with a firelighter.', 10),
    Task('Burn Some Food', '', 'Burn any kind of food while trying to cook it.', 10),
    Task('Burn Some Normal Logs', '', 'Burn some Normal Logs.', 10),
    Task('Burn Some Oak Logs', '', 'Burn some Oak Logs.', 10),
    Task('Bury Some Bones', '', 'Bury any kind of Bones.', 10),
    Task('Buy Something From Trader Crewmembers', '', 'Buy something from the Trader Crewmembers.', 10),
    Task('Cast Home Teleport', '', 'Cast the Home Teleport spell.', 10),
    Task('Catch a Baby Impling', '', 'Catch a Baby Impling.', 10),
    Task('Catch a Butterfly', '', 'Catch any butterfly.', 10, 'k | z | f | v'),
    Task('Catch a Herring', '', 'Catch a Raw Herring whilst Fishing.', 10),
    Task('Catch a Shrimp', '', 'Catch Raw Shrimp while Fishing.', 10),
    Task('Catch an Anchovy', '', 'Catch a Raw Anchovy whilst Fishing.', 10),
    Task('Check Your Slayer Task', '', 'Use an Enchanted Gem to check your Slayer Task.', 10),
    Task('Chop Some Logs With a Steel Axe', '', 'Chop any kind of logs using a Steel Axe.', 10),
    Task('Chop Some Logs', '', 'Chop any kind of logs.', 10),
    Task('Clean a Grimy Guam', '', 'Clean a Grimy Guam.', 10),
    Task('Complete 1 Slayer Task', '', 'Complete 1 Slayer Task.', 10),
    Task('Complete a Rooftop Agility Course', '', 'Complete a lap of any Rooftop Agility Course.', 10),
    Task('Complete the Leagues Tutorial', '', 'Complete the Leagues Tutorial and begin your adventure.', 10),
    Task('Cook Shrimp', '', 'Cook Raw Shrimp.', 10),
    Task('Craft a Leather Body', '', 'Craft a Leather Body.', 10, 'a | k | z | d | m | f'),
    Task('Craft Any Rune', '', 'Use a Runecrafting Altar to craft any type of rune from Essence.', 10),
    Task('Create a Compost Potion', '', 'Create a Compost Potion.', 10),
    Task('Create an Antipoison', '', 'Create an Antipoison.', 10),
    Task('Cry in a wheat field', '', 'Cry in a wheat field.', 10),
    Task('Cut a Sapphire', '', 'Cut a Sapphire.', 10),
    Task('Dance in a graveyard', '', 'Dance in a graveyard.', 10),
    Task('Defeat a Goblin', '', 'Defeat a Goblin. After all, this still isnt the Goblin League.', 10),
    Task('Defeat a Guard', '', 'Defeat a Guard.', 10),
    Task('Defeat a Moss Giant', '', 'Defeat a Moss Giant.', 10),
    Task('Drink a Strength Potion', '', 'Drink a Strength Potion.', 10),
    Task('Dye a cape orange', '', 'Dye a cape orange.', 10),
    Task('Eat some Purple Sweets', '', 'Eat some Purple Sweets.', 10),
    Task('Enter Puro Puro from Gielinor', '', 'Enter Puro Puro from a crop circle in mainland Gielinor.', 10),
    Task('Enter your Player Owned House', '', 'Enter your Player Owned House.', 10),
    Task('Equip a Full Mithril Set', '', 'Equip a Mithril Platebody, a Mithril Full Helm and either some Mithril Platelegs or a Mithril Plateskirt.', 10),
    Task('Equip a Maple Shortbow', '', 'Equip a Maple Shortbow.', 10),
    Task('Equip a Mithril Weapon', '', 'Equip any Mithril weapon.', 10),
    Task('Equip a Spiny Helmet', '', 'Equip a Spiny Helmet.', 10),
    Task('Equip a Studded Body and Chaps', '', 'Equip a Studded Body along with some Studded Chaps.', 10),
    Task('Equip a Willow Shield', '', 'Equip a Willow Shield.', 10),
    Task('Equip an Elemental Staff', '', 'Equip a basic elemental staff.', 10),
    Task('Equip some Black armour', '', 'Equip either a Black Platebody, some Black Platelegs or a Black Full Helm.', 10),
    Task('Equip some Steel armour', '', 'Equip either a Steel Platebody, some Steel Platelegs or a Steel Full Helm.', 10),
    Task('Fletch 1000 arrow shafts', '', 'Fletch 1000 arrow shafts.', 10),
    Task('Fletch 150 Iron Arrows', '', 'Fletch 150 Iron Arrows.', 10),
    Task('Fletch 25 Oak Stocks', '', 'Fletch 25 Oak Stocks.', 10),
    Task('Fletch an Oak Shortbow', '', 'Fletch an Oak Shortbow.', 10),
    Task('Fletch Some Arrow Shafts', '', 'Fletch some Arrow Shafts.', 10),
    Task('Gain a Unique Item From a Beginner Clue', '', 'Gain a unique item from a Beginner Clue Scroll Reward Casket.', 10),
    Task('Gain a Unique Item From an Easy Clue', '', 'Gain a unique item from an Easy Clue Scroll Reward Casket.', 10),
    Task('Have a conversation with a cat', '', 'Have a conversation with a cat.', 10, 'd | f'),
    Task('Kill a Necromancer', '', 'Kill a Necromancer.', 10, 'k | z'),
    Task('Light a Torch', '', 'Light a Torch.', 10),
    Task('Locate a Runecrafting Altar With a Talisman', '', 'Use any talisman to check the location of a Runecrafting Altar.', 10),
    Task('Make an Attack Potion', '', 'Make an Attack Potion.', 10),
    Task('Make some Flour', '', 'Make some Flour in a windmill.', 10),
    Task('Mine 10 Tin Ore', '', 'Mine 10 Tin Ore.', 10),
    Task('Mine 15 coal', '', 'Mine 15 coal.', 10),
    Task('Mine some Copper Ore', '', 'Mine some Copper Ore.', 10),
    Task('Mine some Ore With a Steel Pickaxe', '', 'Mine any ore using a Steel Pickaxe.', 10),
    Task('Obtain a Bird Nest', '', 'Obtain a Bird Nest whilst cutting down trees.', 10),
    Task('Obtain a Casket from Fishing', '', 'Obtain a Casket from Fishing.', 10),
    Task('Obtain a Gem While Mining', '', 'Obtain any kind of gem whilst Mining a rock.', 10),
    Task('Obtain a Mark of Grace', '', 'Obtain a Mark of Grace from any Rooftop Agility Course.', 10),
    Task('Open 28 Coin Pouches At Once', '', 'Open 28 Coin Pouches at once.', 10),
    Task('Open the Leagues Menu', '', 'Open the Leagues Menu found within the Journal Panel.', 10),
    Task('Pickpocket a Citizen', '', 'Pickpocket a Man or a Woman.', 10),
    Task('Plant Seeds in an Allotment Patch', '', 'Plant some seeds in an Allotment patch.', 10, 'a | m | k | z | t | v'),
    Task('Protect Your Crops', '', 'Pay a farmer to protect any of your crops.', 10),
    Task('Purchase a Player Owned House', '', 'Purchase a Player Owned House.', 10),
    Task('Rake a Farming Patch', '', 'Rake any Farming patch.', 10),
    Task('Reach Base Level 5', '', 'Reach level 5 in every skill.', 10),
    Task('Reach Base Level 10', '', 'Reach level 10 in every skill.', 10),
    Task('Reach Base Level 20', '', 'Reach level 20 in every skill.', 10),
    Task('Reach Combat Level 10', '', 'Reach Combat Level 10.', 10),
    Task('Reach Combat Level 25', '', 'Reach Combat Level 25.', 10),
    Task('Reach Total Level 100', '', 'Reach a Total Level of 100.', 10),
    Task('Reach Total Level 250', '', 'Reach a Total Level of 250.', 10),
    Task('Reach Total Level 500', '', 'Reach a Total Level of 500.', 10),
    Task('Receive a Slayer Task', '', 'Receive a Slayer Task from any Slayer Master.', 10),
    Task('Restore 5 Prayer Points at an Altar', '', 'Restore 5 or more Prayer Points at any altar.', 10),
    Task('Scrape some blue dragonhide', '', 'Scrape some blue dragonhide.', 10),
    Task('Smelt a Bronze Bar', '', 'Use a Furnace to smelt a Bronze Bar.', 10),
    Task('Smelt an Iron Bar', '', 'Use a Furnace to smelt an Iron Bar.', 10),
    Task('Smith 150 Iron Arrowtips', '', 'Use an Anvil to smith 150 Iron Arrowtips.', 10),
    Task('Smith a Bronze full helm', '', 'Use an Anvil to smith a Bronze full helm.', 10),
    Task('Smith a Bronze plateskirt', '', 'Use an Anvil to smith a Bronze plateskirt.', 10),
    Task('Snare a Bird', '', 'Catch any bird with a Bird Snare.', 10),
    Task('Spin a Ball of Wool', '', 'Use a Spinning Wheel to spin a Ball of Wool.', 10),
    Task('Steal a Chocolate Slice', '', 'Steal a Chocolate Slice from a Bakery Stall.', 10, 'f | k | z | v'),
    Task('Steal Some Silk', '', 'Steal some silk from a silk stall.', 10, 'k | z | t | v'),
    Task('Successfully Cook 5 Pieces of Food', '', 'Cook 5 pieces of food in a row without burning them.', 10),
    Task('Successfully Cut a Red Topaz', '', 'Successfully Cut a Red Topaz.', 10),
    Task('Superhuman Strength and Improved Reflexes', '', 'Use both the Superhuman Strength prayer and the Improved Reflexes prayer at the same time.', 10),
    Task('Turn any Logs Into a Plank', '', 'Use a Sawmill to turn Logs into a Plank.', 10),
    Task('Use a herring on a tree', '', 'Not quite of the crimson variety.', 10),
    Task('Visit Deaths Domain', '', 'Visit Deaths Domain.', 10),
    Task('Visit the Rune Essence Mine', '', 'Visit the Rune Essence Mine.', 10),
    Task('Catch a Karambwanji', '', 'Catch a Karambwanji on Karamja.', 10),
    Task('Defeat a Greater Demon on Karamja', '', 'Defeat a Greater Demon on Karamja.', 10),
    Task('Defeat a TzHaar', '', 'Defeat any TzHaar in Mor Ul Rek.', 10),
    Task('Enter the Brimhaven Dungeon', '', 'Enter the Brimhaven Dungeon.', 10),
    Task('Pick a Pineapple on Karamja', '', 'Pick a Pineappleon Karamja.', 10),
    Task('Receive a Slayer Task From Duradel', '', 'Receive a Slayer Task From Duradel in Shilo Village .', 10),
    Task('Receive an Agility Arena Ticket', '', 'Receive an Agility Arena Ticket from the Brimhaven Agility Arena.', 10),
    Task('Build a Bank on Fossil Island', '', 'Build a Bank at the Museum Camp on Fossil Island.', 10),
    Task('Charm Gertrude', '', 'Charm Gertrude.', 10, 'm'),
    Task('Chop a log from a potato tree', '', 'Chop a log from a tree that is curiously in a potato field.', 10),
    Task('Churn some butter', '', 'Use a churn to make some butter.', 10),
    Task('Complete Gertrudes Cat', '', 'Complete the  Gertrudes Cat  quest.', 10),
    Task('Complete Romeo & Juliet', '', 'Complete the  Romeo & Juliet  Quest', 10),
    Task('Complete Sheep Shearer', '', 'Complete the  Sheep Shearer  quest.', 10),
    Task('Complete the Draynor Agility Course', '', 'Complete a lap of the Draynor Rooftop Agility Course.', 10),
    Task('Complete the Natural History Quiz', '', 'Complete the Natural History Quiz in the Varrock Museum.', 10),
    Task('Complete the Varrock Agility Course', '', 'Complete a lap of the Varrock Rooftop Agility Course.', 10),
    Task('Complete Vampyre Slayer', '', 'Complete the  Vampyre Slayer  quest.', 10),
    Task('Craft 50 Water Runes', '', 'Craft 50 Water Runes from Essence at the Water Altar.', 10),
    Task('Defeat the Lesser Demon in the Wizards Tower', '', 'Defeat the Lesser Demon at the top of the Wizards Tower.', 10),
    Task('Enter Draynor Manor', '', 'Enter Draynor Manor through the front door.', 10),
    Task('Enter Zanaris', '', 'Enter the lost city of Zanaris.', 10),
    Task('Equip Some Fancy, Fancier or Fighting Boots', '', 'Equip a pair of Fancy Boots, Fancier Boots or Fighting Boots.', 10),
    Task('Feed a draynor guard some stew', '', 'Feed a Draynor guard some stew in Draynor Village.', 10),
    Task('Fully Unlock the Mycelium Transportation System', '', 'Unlock every destination for the Mycelium Transportation System on Fossil Island.', 10),
    Task('Get a chair to follow you', '', 'Get a chair to follow you.', 10),
    Task('Get your revenge against a Dark Wizard', '', 'Get your revenge against a Dark Wizard, south of Varrock.', 10),
    Task('Have Elsie tell you a story', '', 'Have Elsie tell you a story in Varrock.', 10),
    Task('Have Ned make you some rope', '', 'Have Ned make you some rope using a ball of wool in Draynor Village.', 10),
    Task('Insult Aggie the Witch', '', 'Insult Aggie the Witch in Draynor Village.', 10),
    Task('Milk a cow', '', 'Milk a cow in Lumbridge.', 10),
    Task('Pet a Stray Dog in Varrock', '', 'Pet a Stray Dog in Varrock.', 10),
    Task('Pet the Museum Camp dog', '', 'Pet the dog in the Museum Camp on Fossil Island.', 10),
    Task('Pickpocket a H.A.M. Member', '', 'Pickpocket any H.A.M. member at their hideout.', 10),
    Task('Receive a Slayer Task From Vannaka', '', 'Receive a Slayer Task from Vannaka in Edgeville Dungeon.', 10),
    Task('Slash a web in varrock sewers', '', 'Slash a web in Varrock sewers.', 10),
    Task('Steal From the Varrock Tea Stall', '', 'Steal from the Tea Stall in Varrock.', 10),
    Task('Taste a Dorgeshuun Delicacy', '', 'Taste a Dorgeshuun Delicacy.', 10),
    Task('Travel to Fossil Island', '', 'Take the Museum Barge to Fossil Island.', 10),
    Task('Use a Fairy Ring', '', 'Use any Fairy Ring.', 10),
    Task('Use the Range in Lumbridge Castle', '', 'Use the Range in Lumbridge Castle to cook some food.', 10),
    Task('1 Combat Achievement', '', 'Complete 1 Combat Achievement', 40, ca_tasks=1),
    Task('1 Elite Clue Scroll', '', 'Open a Reward casket for completing an elite clue scroll.', 40),
    Task('1 Hard Clue Scroll', '', 'Open a Reward casket for completing a hard clue scroll.', 40),
    Task('10 Combat Achievements', '', 'Complete 10 Combat Achievements', 40, ca_tasks=10),
    Task('100 Superior Slayer Encounters', '', 'Defeat 100 superior foes while on a Slayer Task.', 40),
    Task('15 Collection log slots', '', 'Obtain 15 unique Collection Log slots.', 40),
    Task('150 Easy Clue Scrolls', '', 'Open 150 Reward caskets for completing easy clue scrolls.', 40),
    Task('150 Medium Clue Scrolls', '', 'Open 150 Reward caskets for completing medium clue scrolls.', 40),
    Task('25 Hard Clue Scrolls', '', 'Open 25 Reward caskets for completing hard clue scrolls.', 40),
    Task('25 Medium Clue Scrolls', '', 'Open 25 Reward caskets for completing medium clue scrolls.', 40),
    Task('25 Superior Slayer Encounters', '', 'Defeat 25 superior foes while on a Slayer Task.', 40),
    Task('30 Collection log slots', '', 'Obtain 30 unique Collection Log slots.', 40),
    Task('5 Collection log slots', '', 'Obtain 5 unique Collection Log slots.', 40),
    Task('75 Easy Clue Scrolls', '', 'Open 75 Reward caskets for completing easy clue scrolls.', 40),
    Task('75 Medium Clue Scrolls', '', 'Open 75 Reward caskets for completing medium clue scrolls.', 40),
    Task('75 Superior Slayer Encounters', '', 'Defeat 75 superior foes while on a Slayer Task.', 40),
    Task('Achieve Your First Level 30', '', 'Reach level 30 in any skill.', 40),
    Task('Achieve Your First Level 40', '', 'Reach level 40 in any skill.', 40),
    Task('Achieve Your First Level 50', '', 'Reach level 50 in any skill.', 40),
    Task('Activate Smite', '', 'Activate Smite in your Prayer book.', 40),
    Task('Build a Mahogany Portal', '', 'Build a Mahogany Portal in a Portal Chamber in your Player Owned House.', 40),
    Task('Build a Waka Canoe', '', 'Build a Waka Canoe.', 40),
    Task('Build an Oak Larder', '', 'Build an Oak Larder in a Kitchen in your Player Owned House.', 40),
    Task('Burn 100 Willow Logs', '', 'Burn 100 Willow Logs.', 40),
    Task('Bury Some Wyvern or Dragon Bones', '', 'Bury either some Wyvern Bones or some Dragon Bones.', 40),
    Task('Cast a Blast Spell', '', 'Cast any blast spell.', 40),
    Task('Cast High Level Alchemy', '', 'Cast the High Level Alchemy spell.', 40),
    Task('Catch 100 Lobsters', '', 'Catch 100 Raw Lobsters whilst Fishing.', 40),
    Task('Catch 50 Salmon', '', 'Catch 50 Raw Salmon whilst Fishing.', 40),
    Task('Catch 50 Swordfish', '', 'Catch 50 Raw Swordfish whilst Fishing.', 40),
    Task('Catch a Swamp Lizard or Salamander', '', 'Catch either a Swamp Lizard or any kind of Salamander.', 40, 'm | d | k | w | v'),
    Task('Check a grown Fruit Tree', '', 'Check the health of any Fruit Tree youve grown.', 40),
    Task('Chop 100 Willow Logs', '', 'Chop 100 Willow Logs from Willow Trees.', 40),
    Task('Chop Some Logs With a Rune Axe', '', 'Chop any kind of logs using a Rune Axe.', 40),
    Task('Chop some Rising Roots', '', 'Chop some Rising Roots spawned via Forestry.', 40),
    Task('Clean a Grimy Avantoe', '', 'Clean a Grimy Avantoe.', 40),
    Task('Complete 50 Laps of a Rooftop Agility Course', '', 'Complete 50 laps of any Rooftop Agility Course.', 40),
    Task('Complete 50 Mahogany homes contracts', '', 'Complete 50  Mahogany homes contracts.', 40),
    Task('Complete a Mahogany homes adept contract', '', 'Complete a  Mahogany homes adept contract.', 40),
    Task('Complete a Mahogany homes beginner contract', '', 'Complete a  Mahogany homes beginner contract.', 40),
    Task('Complete a Mahogany homes novice contract', '', 'Complete a  Mahogany homes novice contract.', 40),
    Task('Complete the Easy Western Provinces Diary', '', 'Complete all of the easy tasks in the  Western Provinces Achievement Diary.', 40, 'k'),
    Task('Complete the Flowering Bush event', '', 'Complete the Flowering Bush event spawned via Forestry.', 40),
    Task('Complete the Medium Western Provinces Diary', '', 'Complete all of the medium tasks in the  Western Provinces Achievement Diary.', 40, 'k'),
    Task('Complete the Pheasant Forestry Event', '', 'Complete the Pheasant event spawned via Forestry.', 40),
    Task('Complete the Ritual Forestry Event', '', 'Complete the Ritual event spawned via Forestry.', 40),
    Task('Complete the Struggling Sapling event', '', 'Complete the Struggling Sapling event spawned via Forestry.', 40),
    Task('Cook 100 Lobsters', '', 'Cook 100 Raw Lobsters.', 40),
    Task('Craft 100 Unpowered Orbs', '', 'Craft 100 Unpowered Orbs.', 40),
    Task('Craft 200 Essence Into Runes', '', 'Use Runecrafting Altars to craft 200 essence into runes of any type.', 40),
    Task('Craft 4 Runes With 1 Essence', '', 'Use a Runecrafting Altar to craft 4 of any type of rune using a single essence.', 40),
    Task('Craft a Ruby Amulet', '', 'Craft a Ruby Amulet.', 40),
    Task('Craft an Emerald Ring', '', 'Craft an Emerald Ring.', 40),
    Task('Craft Any Combination Rune', '', 'Use a Runecrafting Altar to craft any type of combination rune.', 40),
    Task('Create a green dhide shield', '', 'Create a green dhide shield.', 40),
    Task('Create a Guthix Rest Tea', '', 'Create a Guthix Rest Tea.', 40, 'f | d | k'),
    Task('Create a Mithril Grapple', '', 'Create a Mithril Grapple.', 40),
    Task('Defeat a Lesser Demon', '', 'Defeat a Lesser Demon.', 40),
    Task('Defeat a Superior Slayer Creature', '', 'Defeat any Superior Slayer Creature.', 40),
    Task('Defeat an Adult Chromatic Dragon', '', 'Defeat either an adult Green Dragon, Blue Dragon, Red Dragon or Black Dragon.', 40),
    Task('Equip a frog mask', '', 'Equip a frog mask.', 40),
    Task('Equip a Full Adamant Set', '', 'Equip an Adamant Platebody, a Adamant Full Helm and either some Adamant Platelegs or an Adamant Plateskirt.', 40),
    Task('Equip a Full Blue Dragonhide Set', '', 'Equip a Blue Dragonhide Body, some Blue Dragonhide Chaps and some Blue Dragonhide Vambraces.', 40),
    Task('Equip a Full Green Dragonhide Set', '', 'Equip a Green Dragonhide Body, some Green Dragonhide Chaps and some Green Dragonhide Vambraces.', 40),
    Task('Equip a Full Red Dragonhide Set', '', 'Equip a Red Dragonhide Body, some Red Dragonhide Chaps and some Red Dragonhide Vambraces.', 40),
    Task('Equip a Full Rune Set', '', 'Equip a Rune Platebody, a Rune Full Helm and either some Rune Platelegs or a Rune Plateskirt.', 40),
    Task('Equip a Granite Shield', '', 'Equip a Granite Shield.', 40, 'k | a | f'),
    Task('Equip a Harpie Bug Lantern', '', 'Equip a Harpie Bug Lantern.', 40),
    Task('Equip a Lava Battlestaff', '', 'Equip a Lava Battlestaff.', 40, 'k | a | w | m | d'),
    Task('Equip a Leaf-Bladed Sword', '', 'Equip a Leaf-Bladed Sword.', 40, 'f | t'),
    Task('Equip a Piece of a Mystic Set', '', 'Equip any piece of any Mystic robe set.', 40),
    Task('Equip a Rune Weapon', '', 'Equip any Rune weapon.', 40),
    Task('Equip a Trimmed Amulet', '', 'Equip a Trimmed Amulet.', 40),
    Task('Equip a Wizard Robe and Hat', '', 'Equip any wizard robe along with any wizard hat', 40),
    Task('Equip a Yew Shortbow', '', 'Equip a Yew Shortbow.', 40),
    Task('Equip an Adamant Weapon', '', 'Equip any Adamant weapon.', 40),
    Task('Equip an Elemental Battlestaff or Mystic Staff', '', 'Equip either an elemental battlestaff or an elemental mystic staff.', 40),
    Task('Equip full Graahk, Larupia or Kyatt', '', 'Equip a full set of Graahk, Larupia or Kyatt attire.', 40),
    Task('Ferment 100 Jugs of Wine', '', 'Successfully ferment 100 Jugs of Wine.', 40),
    Task('Fill 3 Elite Clue Collection Log Slots', '', 'Fill 3 slots in the Elite Clue section of the Collection Log.', 40),
    Task('Fill 3 Hard Clue Collection Log Slots', '', 'Fill 3 slots in the Hard Clue section of the Collection Log.', 40),
    Task('Fill 5 Beginner Clue Collection Log Slots', '', 'Fill 5 slots in the Beginner Clue section of the Collection Log.', 40),
    Task('Fill 5 Easy Clue Collection Log Slots', '', 'Fill 5 slots in the Easy Clue section of the Collection Log.', 40),
    Task('Fill 5 Medium Clue Collection Log Slots', '', 'Fill 5 slots in the Medium Clue section of the Collection Log.', 40),
    Task('Fill a Bucket With Supercompost', '', 'Fill a Bucket with Supercompost from a Compost Bin.', 40, 'a | m | k | z | t | v'),
    Task('Fill a Large Pouch', '', 'Fill a Large Pouch with Essence.', 40),
    Task('Fill a Medium S.T.A.S.H. Unit', '', 'Build a Medium S.T.A.S.H. unit and fill it with the relevant items.', 40),
    Task('Fletch 100 Yew shortbows', '', 'Fletch 100 Yew shortbows.', 40),
    Task('Fletch a Willow Shortbow', '', 'Fletch a Willow Shortbow.', 40),
    Task('Fletch some Broad Arrows or Bolts', '', 'Fletch either some Broad Arrows or some Broad Bolts.', 40),
    Task('Fully deplete a Blood Essence', '', 'Fully deplete a Blood Essence.', 40, 'am | dm | dz | az'),
    Task('Gain 10 Unique Items From Beginner Clues', '', 'Gain 10 unique items from Beginner Clue Scroll Reward Caskets.', 40),
    Task('Gain 10 Unique Items From Easy Clues', '', 'Gain 10 unique items from Easy Clue Scroll Reward Caskets.', 40),
    Task('Gain 10 Unique Items From Medium Clues', '', 'Gain 10 unique items from Medium Clue Scroll Reward Caskets.', 40),
    Task('Gain 5 Unique Items From Hard Clues', '', 'Gain 5 unique items from Hard Clue Scroll Reward Caskets.', 40),
    Task('Gain a Unique Item From a Hard Clue', '', 'Gain a unique item from a Hard Clue Scroll Reward Casket.', 40),
    Task('Gain a Unique Item From a Medium Clue', '', 'Gain a unique item from a Medium Clue Scroll Reward Casket.', 40),
    Task('Harvest an Irit Leaf', '', 'Harvest an Irit Leaf from any Herb patch.', 40, 'a | m | k | f | z | v'),
    Task('Kill 6 cows in 10 seconds', '', 'Kill 6 cows in 10 seconds.', 40),
    Task('Kill three chickens in 6 seconds.', '', 'Kill three chickens in 6 seconds.', 40),
    Task('Light a Bullseye Lantern', '', 'Light a Bullseye Lantern.', 40),
    Task('Make 30 Prayer Potions', '', 'Make 30 Prayer Potions.', 40),
    Task('Make a 4 dose potion', '', 'Make any 4 dose potion using an Amulet of Chemistry.', 40),
    Task('Make a Pineapple Pizza', '', 'Make a Pineapple Pizza.', 40),
    Task('Mine 50 Iron Ore', '', 'Mine 50 Iron Ore.', 40),
    Task('Mine some Ore With a Rune Pickaxe', '', 'Mine any ore using a Rune Pickaxe.', 40),
    Task('Obtain 800 Coins From Coin Pouches At Once', '', 'Open a stack of Coin Pouches and obtain at least 800 Coins.', 40),
    Task('Obtain a Clue Geode While Mining', '', 'Obtain any kind of clue geode whilst Mining a rock.', 40),
    Task('Perform a Special Attack', '', 'Perform any special attack.', 40),
    Task('Pickpocket a Guard', '', 'Pickpocket a Guard.', 40),
    Task('Pickpocket a Master Farmer', '', 'Successfully pickpocket from a Master farmer.', 40),
    Task('Pickpocket a Ranarr Seed', '', 'Pickpocket a Ranarr Seed from a Master Farmer.', 40),
    Task('Reach a Prayer Bonus of 15', '', 'Equip enough item to reach a Prayer bonus of 15 or more.', 40),
    Task('Reach Base Level 30', '', 'Reach level 30 in every skill.', 40),
    Task('Reach Base Level 40', '', 'Reach level 40 in every skill.', 40),
    Task('Reach Base Level 50', '', 'Reach level 50 in every skill.', 40),
    Task('Reach Combat Level 50', '', 'Reach Combat Level 50.', 40),
    Task('Reach Combat Level 75', '', 'Reach Combat Level 75.', 40),
    Task('Reach Total Level 750', '', 'Reach a Total Level of 750.', 40),
    Task('Reach Total Level 1000', '', 'Reach a Total Level of 1000.', 40),
    Task('Reach Total Level 1250', '', 'Reach a Total Level of 1250.', 40),
    Task('Read a prayer book near a lectern', '', 'Read a Prayer book near a lectern.', 40, 'm | f'),
    Task('Slay 250 Creatures', '', 'Slay 250 creatures whilst on a Slayer Task.', 40),
    Task('Smelt a Steel Bar', '', 'Use a Furnace to smelt a Steel Bar.', 40),
    Task('Smith 10 Steel bolts (unf)', '', 'Use an Anvil to smith 10 Steel bolts (unf).', 40),
    Task('Smith a Steel Platebody', '', 'Use an Anvil to smith a Steel Platebody.', 40),
    Task('Teleport Using Law Runes', '', 'Cast any teleport spell that uses Law Runes.', 40),
    Task('Use the Protect from Melee Prayer', '', 'Use the Protect from Melee Prayer.', 40),
    Task('Equip a Dorgeshuun Crossbow', '', 'Equip a Dorgeshuun Crossbow.', 40),
    Task('Buy a Snapdragon From Pirate Jackie the Fruit', '', 'Buy a Snapdragon From Pirate Jackie the Fruit in Brimhaven.', 40),
    Task('Catch 50 Karambwan', '', 'Catch 50 Karambwan on Karamja.', 40),
    Task('Catch a Salmon on Karamja', '', 'Catch a Salmon on Karamja.', 40),
    Task('Complete the Easy Karamja Diary', '', 'Complete all of the easy tasks in the  Karamja Achievement Diary.', 40),
    Task('Complete the Medium Karamja Diary', '', 'Complete all of the medium tasks in the  Karamja Achievement Diary.', 40),
    Task('Craft 50 Nature Runes', '', 'Craft 50 Nature Runes from Essence at the Nature Altar.', 40),
    Task('Defeat a Steel Dragon on Karamja', '', 'Defeat a Steel Dragon on Karamja.', 40),
    Task('Enter the Tai Bwo Wannai Hardwood Grove', '', 'Enter the Hardwood Grove in Tai Bwo Wannai.', 40),
    Task('Equip a Full Tai Bwo Wannai Villager Set', '', 'Equip a full set of Tai Bwo Wannai villager clothing.', 40),
    Task('Equip a Matching Tribal Mask and Broodoo Shield', '', 'Equip a matching Tribal Mask and Broodoo Shield.', 40),
    Task('Fill a Crate With Bananas', '', 'Fill a crate with Bananas for Luthas at Musa Point.', 40),
    Task('Mine 5 gem rocks in a row without failing', '', 'Mine 5 gem rocks in a row without failing in Shilo Village .', 40),
    Task('Catch 50 Implings in Puro-Puro', '', 'Catch 50 Implings in Puro-Puro.', 40),
    Task('Chop a Sulliuscep Cap', '', 'Chop a Sulliuscep Cap on Fossil Island.', 40),
    Task('Complete 10 Laps of the Draynor Agility Course', '', 'Complete 10 laps of the Draynor Rooftop Agility Course.', 40),
    Task('Complete 10 Laps of the Varrock Agility Course', '', 'Complete 10 laps of the Varrock Rooftop Agility Course.', 40),
    Task('Complete a Souls Bane', '', 'Complete the  A Souls Bane  quest.', 40),
    Task('Complete a task for the Wise Old Man', '', 'Complete a task for the Wise Old Man in Draynor.', 40),
    Task('Complete a Volcanic Mine Game', '', 'Complete a Volcanic Mine game on Fossil Island.', 40),
    Task('Complete Demon Slayer', '', 'Complete the  Demon Slayer  quest.', 40),
    Task('Complete Rune Mysteries', '', 'Complete the  Rune Mysteries  quest.', 40),
    Task('Complete the Easy Lumbridge & Draynor Diary', '', 'Complete all of the easy tasks in the  Lumbridge & Draynor Achievement Diary.', 40),
    Task('Complete the Easy Varrock Diary', '', 'Complete all of the easy tasks in the  Varrock Achievement Diary.', 40),
    Task('Complete the Medium Lumbridge & Draynor Diary', '', 'Complete all of the medium tasks in the  Lumbridge & Draynor Achievement Diary.', 40),
    Task('Complete the Medium Varrock Diary', '', 'Complete all of the medium tasks in the  Varrock Achievement Diary.', 40),
    Task('Craft 50 Cosmic Runes', '', 'Craft 50 Cosmic Runes from Essence at the Cosmic Altar from Essence.', 40),
    Task('Defeat a Fossil Island Wyvern', '', 'Defeat any type of Wyvern on Fossil Island.', 40),
    Task('Defeat a Wall Beast', '', 'Defeat a Wall Beast in the Lumbridge Swamp Caves.', 40),
    Task('Defeat an Ancient Wyvern', '', 'Defeat an Ancient Wyvern on Fossil Island.', 40),
    Task('Defeat Bryophyta', '', 'Defeat Bryophyta in Varrock Sewers.', 40),
    Task('Defeat Obor', '', 'Defeat Obor in Edgeville Dungeon.', 40),
    Task('Dismantle 20 Filled Bird Houses', '', 'Dismantle 20 filled Bird Houses on Fossil Island.', 40),
    Task('Drink From the Tears of Guthix', '', 'Drink from the Tears of Guthix  in the Lumbridge Swamp Caves.', 40),
    Task('Enter the Cooks Guild', '', 'Enter the Cooks Guild west of Varrock.', 40),
    Task('Equip Some Mithril Gloves', '', 'Equip a pair of Mithril Gloves.', 40, 'ka'),
    Task('Equip the Forestry Basket', '', 'Obtain and Equip the Forestry Basket.', 40),
    Task('Have the wise Old Man get angry with you.', '', 'Have the Wise Old Man get angry with you in Draynor Village.', 40, 'd'),
    Task('Obtain a pufferfish from Drift Net Fishing', '', 'Obtain a pufferfish from Drift Net Fishing.', 40),
    Task('Open the Dark Chest', '', 'Open the Dark Chest.', 40),
    Task('Pan for an Uncut Jade', '', 'Pan for an Uncut Jade.', 40),
    Task('Set up a Yew Bird House', '', 'Set up a Yew Bird House on Fossil Island.', 40),
    Task('Use a Digsite Pendant to Teleport to Fossil Island', '', 'Use a Digsite Pendant to teleport to Fossil Island.', 40),
    Task('Use Enriched Bones on the Strange Machine', '', 'Use Enriched Bones on the Strange Machine on Fossil Island.', 40),
    Task('Win a Game of Soul Wars', '', 'Win a game of Soul Wars.', 40),
    Task('Defeat Scurrius', '', 'Defeat Scurrius.', 40),
    Task('Scurrius Combat Achievements', '', 'Complate all of the Combat Achievements for Scurrius.', 40),
    Task('Equip a Ratbane Weapon', '', 'Equip a Ratbane Weapon.', 40),
    Task('Equip a Rat Bone Weapon', '', 'Equip a Rat Bone Weapon.', 40),
    Task('Equip a Zombie Axe', '', 'Equip a Zombie Axe.', 40, 'a'),
]